aws/eks-anywhere-packages

api/testdata/bundle_two.yaml, go.sum
=> Small cleanups

PROJECT, api/v1alpha1/packagebundlecontroller_webhook.go, api/v1alpha1/packagebundlecontroller_webhook_test.go, config/webhook/manifests.yaml, main.go
https://github.com/aws/modelrocket-add-ons/issues/179
=> Validate the active bundle

charts/eks-anywhere-packages/values.yaml
=> Fixing values for kube-rbac-proxy helm

Makefile
=> Fix gopath for mockgen

pkg/bundle/manager.go
=> Export sort function and use ServerVersion instead of Discovery

Dockerfile
Required for building current dependencies.
=> Update golang builder to 1.17.

pkg/bundle/manager.go
Include some methods on Manager interface to be used in eks-anywhere codebase.
=> Include SortBundleNewestFirst on manager interface

api/testdata/bundle_one.yaml, api/testdata/bundle_two.yaml
=> update harbor package

charts/eks-anywhere-packages/crds/crd.yaml, hack/helm.sh
I forgot about the helm/build which was not upgraded in the other PR
=> Update crd and helm build

Makefile, api/testdata/bundle_one.yaml.digest, api/testdata/bundle_one.yaml.signed, api/testdata/bundle_two.yaml.digest, api/testdata/bundle_two.yaml.signed, api/v1alpha1/packagebundle_webhook.go, api/v1alpha1/webhook_suite_test.go, pkg/signature/manifest.go, pkg/signature/manifest_test.go, pkg/testutil/signature.go
This env var allows overriding the public key used for packages releases
signature validation.
=> Add EKSA_PUBLIC_KEY environment variable

api/v1alpha1/package_types.go, api/v1alpha1/packagebundle.go, api/v1alpha1/packagebundle_test.go, config/crd/bases/packages.eks.amazonaws.com_packages.yaml, controllers/package_controller.go, controllers/package_controller_test.go, pkg/driver/helmdriver.go, pkg/packages/manager.go
=> Install by version and upgrade all on new releases

Makefile, charts/eks-anywhere-packages/README.md, charts/eks-anywhere-packages/templates/deployment.yaml, charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml, charts/eks-anywhere-packages/values.yaml
Using Dev Gallery Address for Bug Bash, and local testing since the dev image is now live.  https://gallery.ecr.aws/l0g8r8j6/eks-anywhere-packages
Also added in the Public Key from Dev account, and the ENV Var to values.
=> Helm bugbash changes  + Public key env var

charts/eks-anywhere-packages/templates/bundle_one.yaml, hack/helm.sh
Add bundle one to the helm chart for now so we have something by default
=> Add bundle one to helm chart for now

api/v1alpha1/package_types.go, config/crd/bases/packages.eks.amazonaws.com_packages.yaml
=> TargetVersion can be omitted if empty

pkg/driver/helmdriver.go, pkg/driver/helmdriver_test.go
=> Removes helm chart installation prefix

charts/eks-anywhere-packages/values.yaml
For the bug bash, we use the test/dev public key.
=> Use the dev public key for now

pkg/packages/manager.go, pkg/packages/manager_test.go
Create a terminal state for errors that doesn't modify the detail
=> Create terminal state for package errors

api/testdata/test.yaml
The config in there never was an array.
=> Fix test.yaml file

OWNERS
=> Add binyamz to owners

generatebundlefile/data/input_120.yaml, generatebundlefile/hack/generate_bundle.sh
=> Cosign fix, bundle update

go.mod, go.sum, pkg/driver/helmdriver.go, pkg/driver/helmdriver_test.go, pkg/driver/mocks/packagedriver.go, pkg/driver/packagedriver.go, pkg/packages/manager.go, pkg/packages/manager_test.go
Closes: https://github.com/aws/eks-anywhere-packages/issues/83
=> Apply config changes to existing packages

api/v1alpha1/package.go, api/v1alpha1/packagebundle.go, api/v1alpha1/webhook_suite_test.go, controllers/package_controller.go, controllers/packagebundle_controller_test.go, controllers/packagebundlecontroller_controller_test.go, generatebundlefile/bundle.go, pkg/bundle/manager.go, pkg/packages/manager.go
Move the hard coded package namespace to the api
=> Move package namespace to api

generatebundlefile/bundle.go, generatebundlefile/input.go
Bundle name to `bundle.yaml`
Lookup for Codebuild build tag, to match bundle name to bundle tag if it's running in CI.
=> Changing bundle filename, and matching name of bundle tag

generatebundlefile/ecr.go
=> Fix lint error for generate

api/testdata/bundle_one.yaml, api/testdata/bundle_one.yaml.digest, api/testdata/bundle_one.yaml.signed, api/testdata/bundle_two.yaml, api/testdata/bundle_two.yaml.digest, api/testdata/bundle_two.yaml.signed, api/v1alpha1/packagebundle_types.go, charts/eks-anywhere-packages/templates/bundle_one.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml, generatebundlefile/bundle.go, generatebundlefile/bundle_test.go, generatebundlefile/input.go, pkg/signature/testdata/packagebundle_valid.yaml, pkg/signature/testdata/packagebundle_valid.yaml.digest, pkg/signature/testdata/packagebundle_valid.yaml.signed, pkg/signature/testdata/pod_valid.yaml.signed
Remove unused kubeVersion from bundle
=> Remove kubeversion from bundle

api/v1alpha1/packagebundle_types.go, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml
Need this bundle ignored state for bundles outside the namespace
=> Add ignored state to bundle

api/v1alpha1/packagebundlecontroller.go, api/v1alpha1/packagebundlecontroller_test.go, controllers/packagebundlecontroller_controller.go, pkg/bundle/manager.go
The api knows what a valid BundleController looks like, it defines it.
=> Move BundleController validation to BundleController

controllers/packagebundle_controller.go, controllers/packagebundle_controller_test.go, controllers/packagebundle_controller_watch_test.go, pkg/bundle/client.go, pkg/bundle/fake/manager.go, pkg/bundle/manager.go, pkg/bundle/mocks/client.go
Move the GetActiveBundleNamespacedName to bundle client
=> Move GetActiveBundleNamespacedName to bundle client

controllers/packagebundlecontroller_controller.go, controllers/packagebundlecontroller_controller_test.go
These old abc var names are driving me nuts
=> Rename abc vars to pbc

api/v1alpha1/packagebundlecontroller_webhook.go, controllers/packagebundlecontroller_controller.go
The other PRs need to merge first
=> Restrict bundles to the eksa-packages namespace

controllers/packagebundle_controller.go, controllers/packagebundle_controller_test.go, pkg/bundle/client.go, pkg/bundle/manager.go, pkg/bundle/mocks/client.go
Move the IsActive method to the client. This should be the last move.
=> Move IsActive to client

generatebundlefile/hack/generate_bundle.sh
=> ci fix for oras make

README.md
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/167
*Description of changes:* Updated `README.md`
=> Add Disclaimer to README

README.md
The URL should be added to the first occurrence of AWS Service Terms
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/167
*Description of changes:* `README.md`
=> Update Disclaimer for README

charts/eks-anywhere-packages/values.yaml
=> Bumping memory of controller in helm chart

controllers/package_controller.go, controllers/packagebundle_controller.go, controllers/packagebundle_controller_test.go, controllers/packagebundlecontroller_controller.go, controllers/packagebundlecontroller_controller_test.go, generatebundlefile/bundle.go, generatebundlefile/main.go, pkg/bundle/client.go, pkg/bundle/fake/manager.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/client.go
Move the IsActive method to the bundle client
=> Move IsActive method to client

generatebundlefile/hack/generate_bundle.sh
This script was doing the exact same things for two different k8s
versions. I extracted that behavior into two orthogonal functions,
then used a loop to remove the duplication.
Future improvements would be to modify the generatebundle binary so
that its output is more predictable, and make the versions in the
input files match the values used here.
Edit: As @TerryHowe pointed out, we should also work towards a place where the files present determine the versions of k8s that we're supporting.
=> Extract functions and use a loop to be DRYer.

pkg/bundle/client_test.go, pkg/bundle/manager_test.go
Closes: #164 
Unit testing was added for IsBundleKnown and LatestBundle for the bundle manager.
Unit Test was created for client with mock interfaces added
Coverage is now at 92% for pkg/bundle. Most of the remaining percentage is in the mock code for client.
=> Adding code coverage for pkg/bundle

generatebundlefile/bundle.go, generatebundlefile/ecr.go, generatebundlefile/ecr_test.go, generatebundlefile/helm.go, generatebundlefile/promote.go
=> Fixing generatebundle ECR tests to work in prow/mocks

generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh
Current CI is broke, this is tested in devstack, and run correctly without storing any tokens, or outputting to build logs.
=> Fixing ci oras commands

pkg/signature/manifest.go, pkg/signature/manifest_test.go
staticcheck pointed out a couple error messages that are not comjpliant
=> Fix results from staticcheck

api/v1alpha1/packagebundle_webhook.go, controllers/package_controller.go, controllers/packagebundle_controller.go, controllers/packagebundlecontroller_controller.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/driver/helmdriver.go
We should use issues to track TODOs and we have issues or don't care about these.
=> Remove a bunch of TODOs

api/v1alpha1/packagebundlecontroller_types.go, pkg/bundle/client.go, pkg/bundle/client_test.go
The packages should come from where the bundle comes from by default.
=> Use registry from PackageBundleController

pkg/bundle/manager.go
I thought there were more of these, but I can't find them now
=> Add comment for SortBundlesDescending

Makefile
filter out fakes and testutils from testing
=> Do not test the tests

generatebundlefile/main.go, generatebundlefile/options.go
This was used when we were using Cosign to sign, but not anymore, cleaning up the code a bit with this removal.
=> Removing signature flag not used anymore

generatebundlefile/sts.go
Changing the sts client connection to more modular for upcoming PR in which we need to create connection with profile to another account.
=> Updating STS client connection

controllers/packagebundlecontroller_controller.go
My IDE hides this stuff from me
=> Remove silly if statement

generatebundlefile/ecr.go, generatebundlefile/ecr_public.go, generatebundlefile/ecr_test.go, generatebundlefile/helm.go, generatebundlefile/main.go, generatebundlefile/options.go, generatebundlefile/promote.go, generatebundlefile/sts.go
Tested in local accounts, will require a few script changes to work in pipeline, splitting into another PR.
Works together with these other PR's.
https://github.com/aws/eks-anywhere-packages/pull/267
https://github.com/aws/eks-anywhere-packages/pull/268
=> Adding support for private ECR deployments

controllers/package_controller.go, controllers/packagebundle_controller.go, controllers/packagebundle_controller_watch_test.go
Limit namespace of lists and a couple other minor fixes
=> Limit other lists to namespace

charts/eks-anywhere-packages/crds/crd.yaml
=> updating helm chart CRD

generatebundlefile/buildspecs/release-buildspec.yml, generatebundlefile/hack/release-public.sh
Name changed when adding support for private ECR releases.
Ran this locally with 2nd account and all worked, and showed up in ECR https://gallery.ecr.aws/c7a4r4e3/harbor/harbor-registry.
```
go run . --public-profile "jonah2" --input "data/input_local.yaml"                                                                                        <aws:default>
{"level":"info","ts":1655855279.300361,"logger":"BundleGenerator","msg":"Using input file to create bundle crds.","Input file":"data/input_local.yaml"}
{"level":"info","ts":1655855279.7453482,"logger":"BundleGenerator","msg":"In Progress: Populating Bundles and looking up Sha256 tags"}
{"level":"info","ts":1655855281.13058,"logger":"BundleGenerator","msg":"In Progress: Writing bundle to output"} …
```
=> Updating scripts for command change

generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_122_prod.yaml
=> Add metallb to the bundle release

generatebundlefile/hack/release-public.sh
Fixing functions to the release script, currently failing due to a few changes since last release.
=> Fixing release script

controllers/packagebundlecontroller_controller.go, pkg/bundle/manager_test.go
=> Do not requeue ignored PBC

controllers/packagebundlecontroller_controller.go, pkg/bundle/client_test.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go
Fix some logs and spelling errors
=> Fix some logs and spelling

controllers/packagebundlecontroller_controller.go
I finally found this const definition way at the bottom
=> Move const default

controllers/packagebundlecontroller_controller.go
Salvaged from my other PR, this logging fix
=> Generalize pbc logging

controllers/packagebundlecontroller_controller_test.go
Create a method to create a PBC for controller tests.
=> Add given method to create pbc for tests

api/v1alpha1/packagebundle.go, api/v1alpha1/packagebundle_test.go, api/v1alpha1/packagebundle_types.go, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/manager.go
=> Add state for invalid bundle name

pkg/bundle/manager.go, pkg/bundle/mocks/manager.go
=> Fix manager comments

charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml, controllers/packagebundlecontroller_controller.go, controllers/packagebundlecontroller_controller_test.go
Closes: https://github.com/aws/eks-anywhere-packages/issues/204
=> Remove default bundle from chart

api/v1alpha1/packagebundlecontroller_types.go, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml
```
% eksctl anywhere get pbc                                   
NAME    ACTIVEBUNDLE   STATE   DETAIL
billy   v1-21-31               
```
=> Add active bundle to print

generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release-public.sh
Closes: https://github.com/aws/eks-anywhere-packages/issues/185
=> Fix bundle login

generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_122_prod.yaml
The Prod ones will change to private ECR once the support is added in the next week or two, but this is just keeping in line with what we have now.
=> Adding emissary to bundle input

generatebundlefile/bundle_types.go
This thing wasn't being used and just noticed it in a search
=> Remove unused struct from gen bundle

api/testdata/package_webhook_bundle.yaml.digest, api/testdata/package_webhook_bundle.yaml.signed
Add these files that get generated all the time.
=> Add digest and sign file for bundle

charts/eks-anywhere-packages/crds/crd.yaml
Update CRDs as generated by kustomize.
This needs to be automated for the future.
=> Update CRDs for the helm chart.

api/v1alpha1/packagebundle_types.go, charts/eks-anywhere-packages/crds/crd.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml
For some reason these comments only get updated in the crd if there are other changes it seems.
=> Fix invalid version again

api/v1alpha1/packagebundlecontroller_types.go, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml
This OCR reference I'm not sure where it came from.
=> Remove OCR reference

api/v1alpha1/package_types.go, api/v1alpha1/packagebundle_types.go, api/v1alpha1/packagebundlecontroller_types.go, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml, config/crd/bases/packages.eks.amazonaws.com_packages.yaml
*Description of changes:* Update API docs so that we can have a consistent format for API reference docs generation.
=> Update API docs

api/v1alpha1/packagebundle_types.go, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml
*Description of changes:* Updated Repository and UpgradeCheckShortInterval description
=> Update Repository and UpgradeCheckShortInterval description

api/v1alpha1/export_test.go, api/v1alpha1/packagebundle_test.go
One of these wasn't used, the other it would be easier to make it public.
=> Remove export test

generatebundlefile/main.go
Several function calls' errors were being ignored, or only logged, when really
the program should have terminated. This aims to fix a few of those
locations.
=> generatebundlefile: Log errors and exit if appropriate.

generatebundlefile/main.go
A follow up to #369.
Several function calls' errors were being ignored, or only logged, when really
the program should have terminated. This aims to fix those locations.
=> generatebundlefile: Log errors and exit if appropriate part 2

main.go, pkg/bundle/manager.go, pkg/webhook/packagebundlecontroller_webhook.go, pkg/webhook/packagebundlecontroller_webhook_test.go
Validate activeBundle is right kubeVersion
=> Active bundle matches k8s version

generatebundlefile/ecr_helper.go
=> Fixing function comment

generatebundlefile/hack/generate_bundle.sh
=> Fixing build script

api/v1alpha1/package_types.go, api/v1alpha1/packagebundle_types.go, api/v1alpha1/packagebundlecontroller_types.go, charts/eks-anywhere-packages/crds/crd.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml, config/crd/bases/packages.eks.amazonaws.com_packages.yaml
*Description of changes:* Update API descriptions based on comments in https://github.com/aws/eks-anywhere/pull/2898
=> Update api descriptions

generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/promote.sh
=> script fix for codebuild job

generatebundlefile/main.go, generatebundlefile/promote.go
Trying to add fix for release pipeline, and better comments to describe when each scenario is occurring within the code.
=> Trying Fix for logic on release with private/public.

charts/eks-anywhere-packages/templates/configmap.yaml, charts/eks-anywhere-packages/templates/cronjob.yaml, charts/eks-anywhere-packages/values.yaml
*Issue #317
Adding in helm chart for deploying cronjob. This is meant to work with a version #318 that is running in a container.
=> Updating helmchart to add template for ecr-refresh cronjob

generatebundlefile/promote.go
Attempt at fixing build pipelines.
=> Another attempt at pipeline build job fixes

generatebundlefile/hack/release.sh
=> Fix for oras login

generatebundlefile/hack/release.sh
Another fix for the oras issue.
=> Trying another release fix

generatebundlefile/hack/release.sh
=> Trying another fix for release

generatebundlefile/hack/docker-ecr-config.json, generatebundlefile/hack/release.sh
Do all bundle generation while logged in to dev account, then export profile to prod before oras push.
=> Trying another time to re-order the steps for Oras

generatebundlefile/README.md
Cleanup and a bit or re-organization.
=> generatebundlefile: README TLC

controllers/package_controller.go, pkg/csset/csset_test.go
Fixed RestClient Group Version for CoreV1 API
=> Group version fix for RestAPI CoreV1

README.md, docs/README.md
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/340
*Description of changes:* Update gating message
=> Update gating message

api/v1alpha1/packagebundlecontroller_types.go, charts/eks-anywhere-packages/crds/crd.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml
Minor point, but the repository does not need to be required and we default it
=> The repository is defaulted but was required

generatebundlefile/main.go
This breaks the one big main function into smaller command-based
functions. 
@jonahjon please take a close look at this, specifically the "all promotion" parts.
=> generatebundlefile: break main into functions

pkg/bundle/client.go, pkg/bundle/client_test.go
Get the cluster name if available, otherwise use the default.
=> Get cluster name from k8s

pkg/authenticator/ecrsecret.go
Fix to use the namespace key instead of values
=> Fix using namespace key instead of the value

pkg/driver/helmdriver.go, pkg/driver/helmdriver_test.go
Address package config changing due to imagePullSecrets being added by helmdriver and thus not matching the original passed in config.
=> Fix issue where config was detected as change for imagePullSecrets

generatebundlefile/data/input_120.yaml, generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_123.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release.sh
=> Adding bundles for supported versions

Makefile
attempt to clean up packages and helm chart if it is there
=> More thorough make uninstall

Makefile
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/365
*Description of changes:* Add crd match check to presubmit
=> Add crd-match-check

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/data/input_release.yaml, generatebundlefile/hack/release.sh
=> Prod packages version pin

ecrtokenrefresher/cmd/ecr-token-refresher/main.go, ecrtokenrefresher/pkg/aws/aws.go
This should prevent job pod from Crash looping
=> Defaulting region to us-west-2 and exit gracefully 

api/v1alpha1/packagebundle_test.go, controllers/packagebundlecontroller_controller_test.go, pkg/driver/helmdriver_test.go
=> Use testify more

controllers/packagebundle_controller_watch_test.go, go.mod, pkg/bundle/manager_test.go, pkg/file/testutil.go
There are I think 4 different ways to make these things, so this removes one.
=> Make test utils consistent

generatebundlefile/data/input_120.yaml, generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_123.yaml
*Description of changes:* Add ADOT project to bundle
=> Add ADOT to bundle

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/data/input_release.yaml
Testing cross region replication.
=> Bumping hello eks anywhere version

pkg/webhook/package_webhook.go
=> Temporary fix

Makefile, generatebundlefile/hack/release.sh
I think we may need this, but need to investigate alternatives first. This does work.
/hold
=> Add gci write to make fmt

pkg/webhook/package_webhook.go
=> Include permanent fix for package webhook

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/data/input_release.yaml
Get the latest emissary changes https://github.com/aws/eks-anywhere-build-tooling/pull/1265  into prod
=> Bumping emissary version

pkg/bundle/client.go
=> Include fix for workload cluster

charts/eks-anywhere-packages/values.yaml, config/manager/manager.yaml
=> Bumping resources for controller 50%

pkg/packages/manager_test.go
This might make the remote management PR easier to review. These are the changes to remove the order dependency from the manager tests.
=> Remove order dependency from tests

generatebundlefile/data/input_release.yaml
=> Add ADOT to input_release

generatebundlefile/README.md, generatebundlefile/ecr.go, generatebundlefile/ecr_public.go
I hastily merged Jonah's PR because he was blocked and Eric had these comments
=> Comments from generate bundle changes

design/remote-management.md
Design for package controller running on the management cluster
=> Add remote management design document

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/data/input_release.yaml
=> Bumping emissary version without requires config

pkg/bundle/client.go, pkg/bundle/client_test.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/client.go
Create cluster package namespaces on PBC reconciliation
=> Create cluster namespaces on reconcile

pkg/authenticator/kubeconfig.go, pkg/authenticator/kubeconfig_test.go
I'd eventually like to get away from creating the files, but the way helm works this is a lot easier.
=> File handling for kubeconfig

generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_123.yaml
Adds cluster-autoscaler to packages bundle.
=> Add cluster-autoscaler to dev packages bundle

controllers/package_controller.go, controllers/packagebundle_controller.go, controllers/packagebundlecontroller_controller.go, controllers/packagebundlecontroller_controller_test.go, pkg/authenticator/mocks/target_cluster_client.go, pkg/authenticator/target_cluster_client.go, pkg/bundle/client.go, pkg/bundle/client_test.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/client.go, pkg/webhook/packagebundlecontroller_webhook.go, pkg/webhook/packagebundlecontroller_webhook_test.go
Make sure we get bundles associated with the appropriate version
=> Add discovery to target cluster client

go.mod, main.go
Closes: https://github.com/aws/eks-anywhere-packages/issues/427
=> Switch logging from epoch to iso-8601 date format

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/data/input_release.yaml
How do we update the hello app for prod?
/hold
=> Update hello eks to 0.1.2

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/data/input_release.yaml
=> Updating hello eks-anywhere to correct tag

generatebundlefile/data/metrics-server/input_promote.yaml
Epic: https://github.com/aws/eks-anywhere/issues/3187
Adds promotion file for metrics server.
=> Add metrics-server promotion file

generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_123.yaml
Epic: https://github.com/aws/eks-anywhere/issues/3187
Adds metrics-server to dev bundle.
=> Add metrics-server to Dev Bundle

docs/testing/e2e-plan.md
=> e2e docs overview

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml
=> Add ADOT to prod bundle

Makefile
The go vet tool, instead of being run explicitly, is merged into the test target. Since go test already runs a chunk of the same checks as go vet[^1], it's more efficient to run it when testing, which is done via the addition of the -vet=all flag to the go test invocation.
Additionally, the go mod tidy call that was part of the vet target isn't required or really useful there, so it's broken out, using Make's built in dependency tracking to trigger it only when needed, during the build target.
[^1]: https://pkg.go.dev/cmd/go@master#hdr-Test_packages
=> Remove extra go vet calls

controllers/package_controller.go, pkg/packages/manager.go
I'm always wondering how this is used and this new method will define that.
=> Add NewManagerContext method

ecrtokenrefresher/cmd/ecr-token-refresher/main.go, ecrtokenrefresher/pkg/aws/aws.go, ecrtokenrefresher/pkg/kubernetes/kubernetes.go, ecrtokenrefresher/pkg/kubernetes/kubernetes_test.go
Adding support for dev account to ecr-token-refresher for E2E test
=> Add dev account support to ecr token refresher

api/v1alpha1/packagebundlecontroller_types.go, charts/eks-anywhere-packages/crds/crd.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml
=> Change 1d to 24h

generatebundlefile/data/metallb/input_promote.yaml
=> Input promote file for metallb

generatebundlefile/bundle_types.go, generatebundlefile/main.go
=> Fixing bundle gen dependencies field

generatebundlefile/data/input_120.yaml, generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_123.yaml
=> Adding metallb crd to bundle

charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml, charts/eks-anywhere-packages/values.yaml
Add ability to set default registries to helm chart
=> Add default registries to helm chart

generatebundlefile/data/input_120.yaml, generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/data/input_release.yaml
Metallb crds package should be called `metallb/crds`
=> Fix input files for metallb-crds

generatebundlefile/data/input_release.yaml
=> Upgrade metallb to prod

generatebundlefile/data/input_release.yaml
=> Fixing format for prod move

generatebundlefile/data/input_release.yaml
=> Add autoscaler and metrics-server images

generatebundlefile/ecr.go, generatebundlefile/ecr_public.go
=> small tweaks for generatebundlefile

generatebundlefile/promote.go
=> changing logic for public profile copy

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml, generatebundlefile/data/input_release.yaml
Bump Metallb for prod release.
=> Upgrade metallb in prod

generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml
Epic: https://github.com/aws/eks-anywhere/issues/3186
Ticket: https://github.com/aws/eks-anywhere/issues/3727
Add cluster-autoscaler to prod bundle.
=> Add cluster-autoscaler to prod bundle

generatebundlefile/data/input_124.yaml, generatebundlefile/data/input_124_prod.yaml, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release.sh
=> Adding bundle support for 1.24

pkg/bundle/manager.go, pkg/bundle/manager_test.go
Fix the update available detail message
=> Fix update available detail

generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
=> Fix for new dev bundle location

pkg/webhook/packagebundle_test.go
I have the key set in my environment and that breaks these tests.
=> Clear public key environment var

Makefile
=> Remove setup-envtest from make

charts/eks-anywhere-packages/values.yaml
helm docs works better with comments
=> Add proper comments for chart

pkg/authenticator/ecrsecret.go, pkg/authenticator/ecrsecret_test.go
- Cleanup previous authentication completed jobs if trying to install/upgrade package.
- Controller now skips creating job if cronjob spec is set to suspend.
=> Cleanup previous authentication jobs and skip on cronjob suspend

docs/registry.md
I cleaned up the registry docs from the original PR and created this document.
=> Add document on registry use

ecrtokenrefresher/pkg/kubernetes/kubernetes.go, pkg/driver/helmdriver.go
* Update helmdriver error message for failing to update config map.
* Update message on ecr-token for failure to include error message.
=> Updating error messages for driver and token-refresher.

charts/eks-anywhere-packages/templates/_helpers.tpl, charts/eks-anywhere-packages/templates/cronjob.yaml, charts/eks-anywhere-packages/templates/deployment.yaml
Reverting previous change as https://github.com/aws/eks-anywhere/pull/4108 will change the values.yaml file to add the new tag.
=> Reverting chart image tag change

generatebundlefile/data/bundles_prod/1-20.yaml, generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_staging/1-20.yaml, generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml
=> Update adot in staging and prod bundles

generatebundlefile/data/bundles_dev/1-21.yaml, generatebundlefile/data/bundles_dev/1-22.yaml, generatebundlefile/data/bundles_dev/1-23.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/promote/emissary/promote.yaml
=> Adding emissary crd to dev bundle

generatebundlefile/data/bundles_staging/1-20.yaml, generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml
=> Replacing registry for staging bundles

generatebundlefile/hack/release_prod.sh
=> Bundle diff check prod pipeline

generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Adding emissary-crds to staging

generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/staging_artifact_move.yaml
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/639
=> Move prometheus to stagingBundle

generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
Cleaning up scripts moving common ones to common.sh
=> Moving common used functions out to common.sh to reduce code

ecrtokenrefresher/pkg/aws/aws.go
=> Re-enabling region support for token refresher

generatebundlefile/data/bundles_prod/1-20.yaml, generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_staging/1-20.yaml, generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/636
*Description of changes:* This is a very minor update on appVersion. Refer to https://github.com/aws/eks-anywhere-build-tooling/pull/1623
=> Update ADOT package version in staging and prod bundle

generatebundlefile/data/promote/metallb/promote.yaml
=> Bump metallb to 0.13.7

generatebundlefile/data/bundles_prod/1-20.yaml, generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_staging/1-20.yaml, generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml
=> Bump metallb to 0.13.7 in prod

generatebundlefile/data/staging_artifact_move.yaml
=> Bump metallb for staging

generatebundlefile/data/prod_artifact_move.yaml
Moving correct images/helm charts to prod account for prod bundle prep.
=> Getting correct image tags into prod accounts for bundles

generatebundlefile/hack/release_prod.sh
=> Bumping prod bundle number by 110

generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml
Bumping to version 3.3 and adding crds chart.
=> Adding emissary crd and bumping emissary version prod

controllers/package_controller.go, pkg/driver/helmdriver.go, pkg/driver/helmdriver_test.go
Remove unused error returned from NewHelm.
=> Remove unused error from NewHelm

generatebundlefile/main.go, generatebundlefile/region.go
- Added k8s version to the namespace element of the cloudwatch metric.
- Added a missed error check
- Re-ordered the SDK client connections to all be together in the execution.
=> Adding k8s version to cloudwatch metrics

generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/639
=> Update prometheus version in staging/prod packageBundle

pkg/webhook/package_webhook.go, pkg/webhook/package_webhook_test.go
Make targetNamespace immutable.
=> Make targetNamespace immutable

generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/prod_artifact_move.yaml
For the Packages support in all regions coming in this patch release.
=> Updating harbor prod version for all regions

generatebundlefile/Makefile, generatebundlefile/bundle.go, generatebundlefile/bundle_test.go, generatebundlefile/bundle_types.go, generatebundlefile/go.mod, generatebundlefile/go.sum
=> Fix comments and various things for generatebundle

api/v1alpha1/package.go, api/v1alpha1/package_test.go
Goes from 27.8%  to 31.7% which isn't huge, but something.
=> Add to test coverage and IsOldNamespace method

charts/eks-anywhere-packages/templates/awssecret.yaml, charts/eks-anywhere-packages/templates/cronjob.yaml, charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml, charts/eks-anywhere-packages/values.yaml
Add two secrets to the helm chart.
=> Add secrets

generatebundlefile/data/bundles_dev/1-25.yaml
=> Fixes file name

pkg/registry/certificates.go, pkg/registry/client_test.go, pkg/registry/credentials_test.go, pkg/registry/storage.go
I don't plan to keep this up forever, but a couple improvements from the CLI
=> Code sync for CLI

charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml, charts/eks-anywhere-packages/values.yaml
Add registry support for CA or self signed cert.
=> Update helm chart for CA or cert file handling

charts/eks-anywhere-packages/templates/deployment.yaml, charts/eks-anywhere-packages/values.yaml, ecrtokenrefresher/pkg/kubernetes/kubernetes.go, ecrtokenrefresher/pkg/secrets/aws/aws.go, ecrtokenrefresher/pkg/secrets/common/common.go, ecrtokenrefresher/pkg/secrets/common/common_test.go, ecrtokenrefresher/pkg/secrets/registrymirror/registrymirror.go, pkg/authenticator/ecrsecret.go
add authentication mechanism to registry mirrors for helm driver
=> Authentication for helm driver

charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml, charts/eks-anywhere-packages/values.yaml
I'm not sure why there is no insecure option here.
=> Add option for insecure registry

pkg/artifacts/registry.go, pkg/registry/client.go, pkg/registry/client_test.go, pkg/registry/mocks/storage.go, pkg/registry/storage.go
=> Lift registry

generatebundlefile/hack/promote.sh
=> Adding copy images flag when using promote tag for package controller

charts/eks-anywhere-packages/crds/crd.yaml, charts/eks-anywhere-packages/templates/awssecret.yaml, charts/eks-anywhere-packages/templates/certs.yaml, charts/eks-anywhere-packages/templates/clusterrole.yaml, charts/eks-anywhere-packages/templates/clusterrolebinding.yaml, charts/eks-anywhere-packages/templates/configmap.yaml, charts/eks-anywhere-packages/templates/cronjob.yaml, charts/eks-anywhere-packages/templates/deployment.yaml, charts/eks-anywhere-packages/templates/namespace.yaml, charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml, charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml, charts/eks-anywhere-packages/templates/role.yaml, charts/eks-anywhere-packages/templates/rolebinding.yaml, charts/eks-anywhere-packages/templates/service.yaml, charts/eks-anywhere-packages/templates/serviceaccount.yaml, charts/eks-anywhere-packages/templates/servicemonitor.yaml, charts/eks-anywhere-packages/templates/webhook.yaml, charts/eks-anywhere-packages/values.yaml
The new field governs what resource is created for management clusters and workload clusters
=> Add workloadOnly field to helm chart

generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
Using the actual tag in https://gallery.ecr.aws/l0g8r8j6/adot/charts/aws-otel-collector
=> Bumping ADOT tag to actual one in repo

generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
Bumping autoscaler tags to production
=> Bumping cluster autoscaler tag

api/testdata/bundle_one.yaml, api/testdata/bundle_one.yaml.digest, api/testdata/bundle_one.yaml.signed, api/v1alpha1/packagebundle_types.go, charts/eks-anywhere-packages/crds/crd.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml, pkg/signature/manifest.go, pkg/signature/testdata/excludes
Reverts aws/eks-anywhere-packages#771
=> Revert "Add tag to bundle images"

charts/eks-anywhere-packages-crds/.helmignore, charts/eks-anywhere-packages-crds/Chart.yaml, charts/eks-anywhere-packages-crds/README.md.gotmpl, charts/eks-anywhere-packages-crds/templates/crd.yaml, hack/helm.sh
This chart contains the CRDs for eks-anywhere-packages. 
Will be used with self-managed package manager
=> Add a new chart (eks-anywhere-packages-crds)

generatebundlefile/promote.go
=> Fixing nil pointer err on accountID for dev images

generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
=> Adding required changes for 1.25 bundles

charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml, ecrtokenrefresher/cmd/ecr-token-refresher/main.go, ecrtokenrefresher/pkg/secrets/registrymirror/registrymirror.go, pkg/artifacts/mocks/puller.go, pkg/artifacts/puller.go, pkg/artifacts/registry.go, pkg/bundle/client.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/registry_client.go, pkg/bundle/registry_client.go, pkg/bundle/registry_client_test.go, pkg/driver/helmdriver.go, pkg/registry/certificates.go
Allow one set of aws secret credential and registry mirror credential only.
=> Registry mirror fix

generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Upgrade metallb base image

generatebundlefile/data/staging_artifact_move.yaml
This one was missing from the artifact move to staging.
=> Adding new tag to staging artifact mv

generatebundlefile/data/bundles_prod/1-21.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml
=> Bumping metallb in prod tag

generatebundlefile/data/staging_artifact_move.yaml
Move Packages latest release to artifact move, so we can start scanning images better.
It's a static tag now since that was the last release candidate image to go to prod.
=> Adding packages to staging artifact move file

generatebundlefile/data/staging_artifact_move.yaml
=> Fixing typo to use helm tag no images tag.

generatebundlefile/data/staging_artifact_move.yaml
We need to use the corresponding Private ECR tag, not the public one for the copy helm charts.
=> Using private ECR tag not public

go.mod
Link to PR holding everything up.
=> Add link to helm pr we are waiting on

generatebundlefile/go.mod, generatebundlefile/go.sum, go.mod, go.sum
The helm thing is bogging us down here, but this should resolve the other CVEs
=> Docker distribution

generatebundlefile/data/promote/eks-anywhere-packages/promote.yaml
Promote new eksa-packages charts
=> Promote eksa-packages charts

generatebundlefile/data/promote/eks-anywhere-packages/promote.yaml
=> Fixing repo names for packages promote

generatebundlefile/data/bundles_dev/1-22.yaml, generatebundlefile/data/bundles_dev/1-23.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/bundles_dev/1-25.yaml
*Description of changes:* Fix wrong names in bundle.
=> Fix repo name in dev bundle

charts/eks-anywhere-packages/templates/deployment.yaml
Level 6 logging gets all the appropriate data and does not overwhelm.
=> Up the logging for package controller

pkg/bundle/manager.go
If there is no active bundle, the state machine gets  stuck
=> Clear the state if no bundle

generatebundlefile/data/bundles_dev/1-22.yaml, generatebundlefile/data/bundles_dev/1-23.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/bundles_dev/1-25.yaml
=> Fix wrong repo name in bundle

cmd/server.go, pkg/config/config.go
Print effective config at startup and fix var/const for constants.
=> Print config at startup

generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/staging_artifact_move.yaml, generatebundlefile/hack/release_staging.sh
=> Adding 1.26 bundles to staging

charts/eks-anywhere-packages/templates/awssecret.yaml, charts/eks-anywhere-packages/templates/namespace.yaml
*Description of changes:* Lookup since we keep the namespace and might have it from previous install.
Also fix Secret lookup
=> Wrap cluster-specific namespace in lookup

generatebundlefile/bundle.go, generatebundlefile/bundle_types.go, generatebundlefile/input.go, generatebundlefile/main.go
Add minControllerVersion to the output bundle
=> add minversion to bundle

generatebundlefile/data/bundles_dev/1-22.yaml, generatebundlefile/data/bundles_dev/1-23.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/bundles_dev/1-25.yaml, generatebundlefile/data/bundles_dev/1-26.yaml, generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml
*Description of changes:* Add minControllerVersion to each bundle
=> Set minControllerVersion on all bundles

generatebundlefile/data/promote/eks-anywhere-packages/promote.yaml
=> Adding credential-provider-package to promote file

generatebundlefile/data/bundles_dev/1-22.yaml, generatebundlefile/data/bundles_dev/1-23.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/bundles_dev/1-25.yaml, generatebundlefile/data/bundles_dev/1-26.yaml
=> Adding credential-provider-package to dev bundle

credentialproviderpackage/go.mod, credentialproviderpackage/go.sum
=> Address CVE https://nvd.nist.gov/vuln/detail/CVE-2022-41723

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Update hello package in staging and prod

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Update prometheus package in staging and prod

generatebundlefile/data/promote/emissary/promote.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Bumping emissary 3.5.1 promote/staging

generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml
*Description of changes:* Promoting in staging only, another PR will be cut for prod.
=> Use latest base image for metallb

generatebundlefile/data/staging_artifact_move.yaml
=> Bumping version for staging artifact move

generatebundlefile/data/staging_artifact_move.yaml
=> Reverting artifact move back for image scanning

generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml
Update the staging bundles until staging build for package controller are out.
=> Updating staging until real staging builds out

generatebundlefile/README.md, generatebundlefile/bundle_types.go, generatebundlefile/data/staging_artifact_move.yaml, generatebundlefile/input.go, generatebundlefile/main.go, generatebundlefile/promote.go
Will have a followup PR replacing the existing `copyImages` feature in promote with this field.
=> Copyimages added to public profile flag

generatebundlefile/data/staging_artifact_move.yaml
=> Copyimages for migrations helm chart

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Bumping emissary to 3.5.1 for staging/prod

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/hack/release_prod.sh
=> Updating versions for prod bundles

generatebundlefile/data/staging_artifact_move.yaml
Copy release chart images over to private ECR.
=> Copy release prod chart images to private ECR

generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Using correct version for controller

generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
Reverts aws/eks-anywhere-packages#913
=> Revert "Using correct version for controller"

generatebundlefile/hack/release_staging.sh
The order got messed up last week with the bundle changes made.
=> Moving region-check after bundle creation

generatebundlefile/hack/release_staging.sh
=> Put region check after bundle creation

generatebundlefile/data/staging_artifact_move.yaml
=> Moving specific sha for token refresher to private

generatebundlefile/go.mod, generatebundlefile/go.sum, go.mod, go.sum
=> Updating docker cli dependency version

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml
Promotes the images built here: https://github.com/aws/eks-anywhere-build-tooling/pull/2085
https://github.com/aws/eks-anywhere-build-tooling/issues/2092
https://github.com/aws/eks-anywhere-build-tooling/issues/2084
=> Fix Autoscaler CVEs

generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Using correct versions for bundles

generatebundlefile/data/promote/metrics-server/promote.yaml
=> Fix metrics-server promote logic

generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml
=> Update cert-manager version

generatebundlefile/data/promote/emissary/promote.yaml
=> Updating emissary to 3.6.0 dev bundle

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Update bundle for prometheus and harbor

credentialproviderpackage/charts/credential-provider-package/templates/_helpers.tpl, credentialproviderpackage/charts/credential-provider-package/templates/daemonset.yaml
Reverts aws/eks-anywhere-packages#943
=> Revert "Support for Ubuntu 22.04 in credential package"

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
Version being used wasn't in https://gallery.ecr.aws/l0g8r8j6/metallb/metallb, updating to recent version.
=> Using metallb image in public ECR for promotion

credentialproviderpackage/pkg/configurator/linux/linux.go, credentialproviderpackage/pkg/configurator/linux/linux_test.go
=> Changing linux api version for credential package

credentialproviderpackage/pkg/configurator/linux/linux.go, credentialproviderpackage/pkg/configurator/linux/linux_test.go
=> Adjusting api version by -1 for e2e tests

credentialproviderpackage/pkg/configurator/linux/linux.go, credentialproviderpackage/pkg/configurator/linux/linux_test.go
=> Changing api version for double cloud provider version

generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Update 1.27 package bundles

generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
=> Update scripts for 1.27

credentialproviderpackage/pkg/configurator/linux/linux.go
ecrCredProviderBinary needs to fetch two different versions of binary based on the k8 version
=> Update ecrCredProviderBinary path

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Update credential package version in bundle

credentialproviderpackage/charts/credential-provider-package/templates/_helpers.tpl, credentialproviderpackage/charts/credential-provider-package/templates/daemonset.yaml
This reverts commit 51dd0f4ac2969cf9f1554dc155440644857c0323.
=> Revert "Revert "Support for Ubuntu 22.04 in credential package (#943)" "

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Updating packages for patch release

generatebundlefile/data/bundles_dev/1-22.yaml, generatebundlefile/data/bundles_dev/1-23.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/bundles_dev/1-25.yaml, generatebundlefile/data/bundles_dev/1-26.yaml, generatebundlefile/data/bundles_dev/1-27.yaml, generatebundlefile/data/promote/eks-anywhere-packages/promote.yaml
=> Updating bundles to use dev built credential package

pkg/bundle/manager.go
=> Fixing false error logging

generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Bump packages-controller tags

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Bump tags for prod

generatebundlefile/data/bundles_prod/1-22.yaml, generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Bump harbor version in prod release

generatebundlefile/data/bundles_dev/1-28.yaml
Adds support for 1.28 packages
=> Add 1-28 Dev Bundle Support

pkg/registry/ecr_cred_injector.go
=> Fixup: return nil when registry is not ECR

generatebundlefile/data/promote/autoscaler/promote.yaml, generatebundlefile/data/promote/metrics-server/promote.yaml, generatebundlefile/hack/generate_bundle.sh
=> Add 1 28 dev support

pkg/registry/ecr_cred_injector.go
=> fix aws-secret path

generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml, generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
=> Update 1.28 package bundles

generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Fix 1.28 Prod Image Tags

generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Bump packages tags in staging

generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Fix packages tags in staging

generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Fix Packages in Staging

generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Bump packages in prod

generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Update staging to use properly versioned tags

generatebundlefile/data/bundles_prod/1-23.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Update Prod to use properly versions tags

generatebundlefile/data/bundles_dev/1-24-regional.yaml, generatebundlefile/data/bundles_dev/1-25-regional.yaml, generatebundlefile/data/bundles_dev/1-26-regional.yaml, generatebundlefile/data/bundles_dev/1-27-regional.yaml, generatebundlefile/data/bundles_dev/1-28-regional.yaml, generatebundlefile/ecr.go, generatebundlefile/ecr_helper.go, generatebundlefile/ecr_public.go, generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh
Add packages input files for private ECR bundle generation.
=> Add packages input files for private ECR bundle generation

generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Fix tags in staging

generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Fix tags in prod

generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move.yaml
Bump EKS-A packages SHA in bundles input.
=> Bump EKS-A packages SHA in staging bundles input

generatebundlefile/data/bundles_prod/1-24-regional.yaml, generatebundlefile/data/bundles_prod/1-25-regional.yaml, generatebundlefile/data/bundles_prod/1-26-regional.yaml, generatebundlefile/data/bundles_prod/1-27-regional.yaml, generatebundlefile/data/bundles_prod/1-28-regional.yaml, generatebundlefile/data/prod_artifact_move-regional.yaml, generatebundlefile/hack/release_prod.sh
Adding input and move files for regional prod artifact promotion.
=> Add regional prod artifact move and input files

generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Update staging bundle

generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Update eksa package controller in prod

generatebundlefile/hack/common.sh
=> fixup! Fix empty AWS Profile issueg

generatebundlefile/hack/promote.sh, generatebundlefile/main.go
=> Fix codebuild promo-bundle-aws-eks-anywhere-packages

generatebundlefile/main.go
=> Skip bundle generating when promote flag is on

generatebundlefile/hack/common.sh
=> Fix aws profile

generatebundlefile/data/bundles_staging/1-24-regional.yaml, generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml
=> Bump harbor version in staging regional ECR

generatebundlefile/data/bundles_staging/1-24-regional.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Bump harbor version in staging

generatebundlefile/data/bundles_prod/1-24-regional.yaml, generatebundlefile/data/bundles_prod/1-24.yaml, generatebundlefile/data/bundles_prod/1-25-regional.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26-regional.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27-regional.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28-regional.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/prod_artifact_move-regional.yaml, generatebundlefile/data/prod_artifact_move.yaml
=> Bump harbor version in prod

README.md, Tiltfile, tilt/deployment.yaml
Allows developers to iteratively build against an image
run in a live cluster.
Configures a basic Tiltfile so that developers can work against the repository with live reload against a cluster.
=> Add Tiltfile

generatebundlefile/data/promote/metrics-server/promote.yaml
=> Promote Metrics Server Helm Charts

generatebundlefile/data/bundles_dev/1-24-regional.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/bundles_dev/1-25-regional.yaml, generatebundlefile/data/bundles_dev/1-25.yaml, generatebundlefile/data/bundles_dev/1-26-regional.yaml, generatebundlefile/data/bundles_dev/1-26.yaml, generatebundlefile/data/bundles_dev/1-27-regional.yaml, generatebundlefile/data/bundles_dev/1-27.yaml, generatebundlefile/data/bundles_dev/1-28-regional.yaml, generatebundlefile/data/bundles_dev/1-28.yaml, generatebundlefile/data/promote/autoscaler/promote.yaml
=> Bump cluster-autoscaler to latest on dev and promote helm chart for autoscaler

generatebundlefile/data/promote/emissary/promote.yaml
Reverts aws/eks-anywhere-packages#1052
=> Revert "Revert emissary to 3.6.0"

generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml
=> Bump AutoScaler and Metrics server version to latest for staging bundles

generatebundlefile/data/bundles_staging/1-24-regional.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml
Update cert-manager in staging bundle
=> Update cert-manager in staging bundle

generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml
=> Fix metallb staging version for regional builds

generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml
=> Fix ECR image tags for cluster auto-scaler and metrics server for regional builds

generatebundlefile/data/bundles_dev/1-29-regional.yaml, generatebundlefile/data/bundles_dev/1-29.yaml, generatebundlefile/data/promote/autoscaler/promote.yaml, generatebundlefile/data/promote/metrics-server/promote.yaml, generatebundlefile/hack/generate_bundle.sh
Add v1.29 dev packages bundles input.
=> Add v1.29 dev packages bundles input

generatebundlefile/hack/common.sh, generatebundlefile/main.go
=> Fix AWS profile for release jobs

generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/promote/eks-anywhere-packages/promote.yaml, generatebundlefile/data/staging_artifact_move.yaml
Fix ECR public missing tags for packages staging release
=> Fix tags for packages staging release

generatebundlefile/data/staging_artifact_move.yaml
Adding back copy images true to staging.
=> Adding back copy images true to staging

generatebundlefile/data/prod_artifact_move.yaml
Adding back copy images for prod packages move.
=> Adding back copy images for prod packages move

OWNERS
=> Add sp1999 to OWNERS

generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29-regional.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml
Bumping up staging versions for eks-anywhere-packages to latest tagged build.
=> Bumping staging versions for eks-anywhere-packages

generatebundlefile/data/bundles_prod/1-25-regional.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26-regional.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27-regional.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28-regional.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29-regional.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/prod_artifact_move-regional.yaml, generatebundlefile/data/prod_artifact_move.yaml
Staging build was successful. Bumping prod tags to latest to trigger a release with latest tags.
=> Bump packages prod release tags

generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29-regional.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml
=> Update packages staging to latest version

generatebundlefile/data/bundles_prod/1-25-regional.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26-regional.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27-regional.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28-regional.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29-regional.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/prod_artifact_move-regional.yaml, generatebundlefile/data/prod_artifact_move.yaml
Bump packages prod bundle to latest version.
=> Bump packages prod to latest version

OWNERS
Add jhaanvi5 to the list of owners.
=> Add jhaanvi5 to owners

generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/bundles_prod/1-30.yaml
Update curated packages PROD to latest version
=> Update packages prod to latest version

generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml
This PR updates curated packages staging bundles to latest version.
=> Update Curated Packages staging bundles to latest version

generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/bundles_prod/1-30.yaml
This PR updates curated packages prod bundles to latest version.
=> Update curated packages prod to latest version

generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/bundles_staging/1-31.yaml
This PR updates Curated Packages Staging bundle to latest version.
=> Update Curated Packages Staging bundle to latest version

generatebundlefile/data/bundles_staging/1-31.yaml
This PR updates curated packages(`eks-anywhere-packages` and `emissary`) to latest version for staging release.
=> Update curated packages to latest for 1.31

generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/bundles_staging/1-31.yaml
This PR updates metrics-server version for staging release.
=> Update metrics-server version for staging release

generatebundlefile/data/bundles_prod/1-31.yaml
* Update curated packages (`eks-anyhwere-packages and emissary`) version for 1.31
=> Update curated packages version for 1.31

generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/bundles_staging/1-31.yaml
This PR updates Curated packages staging bundle to latest.
=> Update Curated packages staging bundle to latest

generatebundlefile/data/bundles_dev/1-32.yaml, generatebundlefile/data/bundles_prod/1-32.yaml, generatebundlefile/data/bundles_staging/1-32.yaml, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
Add 1-32 bundle for dev, staging and prod bundles
=> Add 1-32 bundle for dev, staging and prod bundles

generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/bundles_prod/1-30.yaml, generatebundlefile/data/bundles_prod/1-31.yaml, generatebundlefile/data/bundles_prod/1-32.yaml
Update Curated packages prod bundle to latest
=> Update Curated packages prod bundle to latest

release/buildspecs/release-announce.yml, release/scripts/announce-curated-packages-release.sh
For automated release announcement for curated packages release
- Added buildspec configuration for release announcement CodeBuild job
- Created script to publish release notifications through SNS
=> Add buildspec and script for curated packages release announcement

OWNERS
=> Add vivek-koppuru to owners file

release/scripts/announce-curated-packages-release.sh
- Update script for packages release announcement
=> Update script for packages release announcement

generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/bundles_staging/1-31.yaml, generatebundlefile/data/bundles_staging/1-32.yaml
Upgrade Curated packages (eksa-anywhere-packages) staging bundle to [latest](https://github.com/aws/eks-anywhere-build-tooling/commit/ee8b42c11457d68367c2a937339ba55570e95bc6). Other packages will be updated as part of staging packages release.
=> Upgrade Curated packages (eksa-anywhere-packages) staging bundle to lates

generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/bundles_staging/1-31.yaml, generatebundlefile/data/bundles_staging/1-32.yaml
Update Emissary and Harbor Curated packages to latest version for staging release
=> Update Emissary and Harbor Curated Packages to latest version for staging release

generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/bundles_staging/1-31.yaml, generatebundlefile/data/bundles_staging/1-32.yaml
* Updated autoscaler and metrics-server to latest for staging release
=> Update autoscaler and metrics-server for staging release

generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/bundles_staging/1-31.yaml, generatebundlefile/data/bundles_staging/1-32.yaml
Updating autoscaler to latest for staging
=> [WIP] Updating autoscaler to latest for staging

generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/bundles_prod/1-30.yaml, generatebundlefile/data/bundles_prod/1-31.yaml, generatebundlefile/data/bundles_prod/1-32.yaml
- Update curated packages PROD bundle to latest version
=> Update packages prod to latest version v0.4.6

generatebundlefile/data/bundles_dev/1-33.yaml, generatebundlefile/data/bundles_prod/1-33.yaml, generatebundlefile/data/bundles_staging/1-33.yaml, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
Add 1-33 bundle for dev, staging and prod bundles
=> Add 1-33 bundle for dev, staging and prod bundles

generatebundlefile/data/bundles_dev/1-28.yaml, generatebundlefile/data/bundles_dev/1-29.yaml, generatebundlefile/data/bundles_dev/1-30.yaml, generatebundlefile/data/bundles_dev/1-31.yaml, generatebundlefile/data/bundles_dev/1-32.yaml, generatebundlefile/data/bundles_dev/1-33.yaml
- Update dev bundle for metallb to 0.15.2
=> Update dev bundle for metallb
