aws/eks-anywhere-packages

README.md
I think this would only be needed if we were pushing images and we had state credentials. Probably a `docker logout` would work too.
=> Remove get-login from README

generatebundlefile/README.md, generatebundlefile/bundle.go, generatebundlefile/ecr.go
Tag has been replaced with Digest. Updating some of the classes to reflect the change.
=> Replace Tag with Digest

pkg/driver/helmdriver.go
Helm was upgraded to 3.8 but our helm driver required changes in order to be
compatible. This commit instantiates a `registry.Client` to be placed in the
configuration object and used by Install actions.
=> Updating helm driver to be compatible with helm3.8

pkg/artifacts/registry.go
When our oras was updated, this got missed. Also, we don't need the docker
stuff anymore, oras is enough on its own.
=> Updates bundle puller for new oras

config/webhook/manifests.yaml
This config was thought not to be used, but it is at least used during
the webhook envtests.
=> Restore signature webhook config

charts/eks-anywhere-packages/templates/service.yaml
The webhooks service name did not match the certificate and admission control configuration.
=> Fix chart webhooks

charts/eks-anywhere-packages/crds/crd.yaml, hack/helm.sh
Ideally, we'd want all chart resources to be generate from the kustomize output.
=> Use kustomize's output to generate CRDs for helm

charts/eks-anywhere-packages/templates/deployment.yaml
The env var is defined as plain `true` in the rendered chart, making the deployment fail.
=> Fix chart deployment ENABLE_WEBHOOK env var

api/v1alpha1/packagebundlecontroller_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml, controllers/packagebundlecontroller_controller.go
If the latest bundle download fails, try again in an hour instead of every couple minutes.
=> Provide a terse error message for latest failure

.github/workflows/golangci-lint.yml
Follows from the fix in: https://github.com/aws/eks-anywhere/pull/1732
=> Fix go version used by golangci-lint.

controllers/package_controller.go
I haven't tried it, but this change should stop someone from being able to uninstall your package
=> Only delete packages for CRs in the namespace

config/manager/manager.yaml
We've had reports of the controller getting `OOMKilled`, increasing the limit will prevent that.
I've profiled the controller and I see total usage of the container go up to 101MiB, the controller itself doesn't report much heap usage however. More profiling will be done in the future.
=> Increase resources limit on controller

pkg/bundle/manager.go
Kind of painful to remove this, but this print is deceptive because no relationship has been established between the bundles at this point. We can pull this out of git history if we need, but it is confusing at this point.
=> Remove print from bundle manager

pkg/signature/testdata/sign_file.sh
Signing script fails sometimes because of bash handling of binary data in variables.
=> Fix signing script

Makefile
Command `go get` can no longer be used to build packages starting `Go v1.18` (see [deprecation notice](https://go.dev/doc/go-get-install-deprecation)). Kustomize version also needs to be updated since `go install` doesn't support exclude directives (see [issue](https://github.com/kubernetes-sigs/kustomize/issues/3618)). The change has been tested on both `Go v1.17` and `Go v1.18` to ensure the Makefile works properly.
*Description of changes:* Update `go get` to `go install`, and Kustomize version to `v4.5`.
=> Update install workflow to support Go v1.18

api/testdata/bundle_one.yaml, api/testdata/bundle_one.yaml.signed
Update the name of `hello-eks-anywhere` repository to match an existing version on `public.ecr.aws/l0g8r8j6/hello-eks-anywhere`.
*Issue #, if available:* `v0.1.1-8b3810e1514b7432e032794842425accc837757a-helm` is not a valid name for `hello-eks-anywhere`.
*Description of changes:* Update the name to an existing version on `public.ecr.aws/l0g8r8j6/hello-eks-anywhere`.
=> Update package bundle image

controllers/packagebundle_controller.go, pkg/bundle/fake/manager.go, pkg/bundle/manager.go
Update the `Reconcile` function to support the scenario that if the bundle controller detects that the active bundle is deleted, the bundle controller will validate the active bundle by namespace and name, and re-download the bundle. The changes were tested locally and passed all testing.
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/136
*Description of changes:* `Reconcile` function was updated to support the re-download logic. In order to support this logic, I also added a `GetActiveBundleNamespacedName` function in the `manager`, and updated `manager` `fake` functions. 
=> Add a re-download functionality to Controller

controllers/packagebundle_controller.go
Use the k8s client interface to recreate the bundle.
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/136
*Description of changes:* Add the recreate bundle logic and update format for `Reconcile`.
=> Add a recreate bundle functionality to Controller

pkg/bundle/fake/manager.go, pkg/bundle/manager.go
This method was replaced by GetActiveBundle in the client
=> Remove ActiveBundle method

pkg/bundle/manager.go
*Description of changes:* Updated `manager.go` file. There are more abc references in the repo, but I'm keeping the PR small to avoid conflict.
=> Rename abc vars to pbc for manager.go

pkg/bundle/client.go
*Description of changes:* Updated `client.go` file. There are more abc references in the repo, but I'm keeping the PR small to avoid conflict.
=> Rename abc vars to pbc for client.go

controllers/packagebundlecontroller_controller_test.go
*Description of changes:* Updated `packagebundlecontroller_controller_test.go` file. `PBC` stands for `PackageBundleController`, which ensures better readability.
=> Rename ABC related vars to PBC for controller_test.go

pkg/bundle/manager.go, pkg/bundle/manager_test.go
If a bundle is not active, we should make sure it is marked inactive.
=> Fix active bundle handling

pkg/bundle/manager.go, pkg/bundle/manager_test.go
```
% k get packages,packagebundles,packagebundlecontrollers,packagecontrollers -A
NAMESPACE       NAME                                                  STATE
default         packagebundle.packages.eks.amazonaws.com/v1-21-1003   ignored
eksa-packages   packagebundle.packages.eks.amazonaws.com/v1-21-1001   active (upgrade available)
eksa-packages   packagebundle.packages.eks.amazonaws.com/v1-21-1002   inactive
NAMESPACE       NAME                                                                                 STATE     DETAIL
default         packagebundlecontroller.packages.eks.amazonaws.com/bob                               ignored   
default         packagebundlecontroller.packages.eks.amazonaws.com/eksa-packages-bundle-controller   ignored   
eksa-packages …
```
=> Ignore other namespaces

controllers/packagebundlecontroller_controller.go
```
NAMESPACE       NAME                                                                                 STATE          DETAIL
default         packagebundlecontroller.packages.eks.amazonaws.com/bob                               ignored        
default         packagebundlecontroller.packages.eks.amazonaws.com/eksa-packages-bundle-controller   ignored        
eksa-packages   packagebundlecontroller.packages.eks.amazonaws.com/billy                             ignored        
eksa-packages   packagebundlecontroller.packages.eks.amazonaws.com/eksa-packages-bundle-controller   disconnected  
```
Closes: #109
=> Disconnected

pkg/bundle/manager.go, pkg/bundle/manager_test.go
Rename the `SortBundlesNewestFirst` method to `SortBundlesDescending`. Though the current sorting logic does represent "NewestFirst", this sorting logic needs to be further tuned (and may be subject to changes). Before we re-tune the logic, we want to rename the method to a more generic name "SortBundlesDescending" to avoid confusion for users.
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/166
*Description of changes:* Rename method `SortBundlesNewestFirst`
=> Sort bundles numerically

charts/eks-anywhere-packages/templates/packagebundle.yaml, charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml
=> Adding bundle to helm chart for active Bundle

api/testdata/bundle_one.yaml, api/testdata/bundle_one.yaml.digest, api/testdata/bundle_one.yaml.signed, api/testdata/bundle_two.yaml, api/testdata/bundle_two.yaml.digest, api/testdata/bundle_two.yaml.signed, api/testdata/harbor.yaml, api/testdata/test.yaml, pkg/bundle/manager_test.go
With these updated examples, the installs are working for me
```
% k get packages,packagebundles,packagebundlecontrollers -A
NAMESPACE       NAME                                         PACKAGE   AGE   STATE       CURRENTVERSION                                   TARGETVERSION                                             DETAIL
eksa-packages   package.packages.eks.amazonaws.com/my-test   test      8s    installed   0.1.1-6d0e566362d03a00f41d75524d21de5ddb95fd1d   0.1.1-6d0e566362d03a00f41d75524d21de5ddb95fd1d (latest)   
NAMESPACE       NAME                                                  STATE
eksa-packages   packagebundle.packages.eks.amazonaws.com/v1-21-1001   active
NAMESPACE       NAME                                                                                 STATE …
```
=> Update examples with latest from dev build

generatebundlefile/ecr.go, generatebundlefile/promote.go
Tags not sync'd when copying over to Prod, trying a fix which doesn't require a new build. Otherwise we need to revert the bundle in the helm chart to `v1-22-4` since `v1-22-5` is showing newer sha sums which are not in Prod yet.
=> prod tag fix

generatebundlefile/Makefile, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release.sh
The creation of the directory is being performed in scripts, but they
shouldn't need to worry about things like this. Move it to the
Makefile where it belongs.
=> Ensure that the output directory exists.

api/v1alpha1/export_test.go, api/v1alpha1/packagebundle.go, api/v1alpha1/packagebundle_test.go, controllers/packagebundle_controller.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go
If the version of the bundle doesn't match the specified Kubernetes version, the PackageBundle state will be marked as `PackageBundleStateIgnored`.
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/138
*Description of changes:* Add `KubeVersionMatches` method, helper function `GetMajorMinorFromString`; and update `Update` in manager.go
=> Add KubeVersion check to PackageBundle State

generatebundlefile/hack/common.sh, generatebundlefile/hack/release.sh
This extends the work performed in
https://github.com/aws/eks-anywhere-packages/pull/210 to use the
orasAuth function in more places. The calling convention has changed a
little, as the new awsAuth function no longer wraps the oras call, but
rather it calls whatever command is passed to it. This eliminates the
need for the awsAuth function to know anything about the paths where
binaries can be found.
=> Extract awsAuth function and use it in more places

generatebundlefile/bundle.go, generatebundlefile/bundle_test.go, generatebundlefile/ecr.go, generatebundlefile/ecr_test.go, generatebundlefile/go.mod, generatebundlefile/go.sum, generatebundlefile/input.go, generatebundlefile/main.go, generatebundlefile/promote.go
This is moving toward creating our clients in main, so that our tests
can rely on interfaces that need not implement everything in the
client, but rather only the methods we call.
This is not the end goal. But it's a step in the right direction to 
getting the AWS client abstracted enough that we can use an 
interface instead. More lifting of logic is required, and will be 
coming in future commits.
=> Extract AWS config

generatebundlefile/bundle_types.go, generatebundlefile/ecr.go, generatebundlefile/helm.go, generatebundlefile/input.go, generatebundlefile/main.go
Adding in the Config/Images to bundle creation, requires using the helm driver during bundle creation, so moved around the authfile creation a bit so it wouldn't be duplicated on releases too. 
Everything is tested in dev account pipeline, although my dev harbor build is older so it doesn't have all the config values.
```
apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: PackageBundle
metadata:
annotations:
eksa.aws.com/excludes: LnNwZWMucGFja2FnZXNbXS5zb3VyY2UucmVnaXN0cnkKLnNwZWMucGFja2FnZXNbXS5zb3VyY2UucmVwb3NpdG9yeQo=
eksa.aws.com/signature: MEQCIGXNYvwgo38cwuXl7H1ybG9uDfpmXp68hbkVn+/LXG5qAiBpziFMbIOdmiIvLIjcCc9D7gg30cNxfDA9Eg/u8YALMw==
name: v1-21-30
namespace: eksa-packages
spec: …
```
=> Adding config, and images to bundle creation

api/v1alpha1/packagebundle_types.go, config/crd/bases/packages.eks.amazonaws.com_packagebundles.yaml, generatebundlefile/bundle.go, generatebundlefile/bundle_test.go
The registry in the bundle should not be provided unless we want to override it. This change is to support private registries.
=> Make registry optional in bundle

controllers/packagebundle_controller.go, controllers/packagebundle_controller_test.go, pkg/bundle/fake/manager.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/manager.go
Use of bundle list in controller was not filtering by namespace and this change uses a common method to get the list.
Slight added benefit that we don't get the bundle list unless we need to.
Closes: #237
=> Use get bundle list in manager

generatebundlefile/bundle.go, generatebundlefile/bundle_types.go, generatebundlefile/ecr.go, generatebundlefile/ecr_helper.go, generatebundlefile/ecr_public.go
As we get ready write functions for new Gating deployment, it made more sense to move functions for ECR, ECR public, and Helper functions into separate files to work with, and read easier. 
No code changes made in this PR just moving stuff around, and 1 rename.
=> Re-ordering code for Gating functions to be added

Makefile
=> Update setup env tests

generatebundlefile/bundle.go, generatebundlefile/main.go
We keep the registry in the PackageBundleSpec until after the lookups are complete, then set it to empty string before doing the signature, and writing to yaml.
=> Fixing pipeline removing registry from bundle output

pkg/bundle/client_test.go, pkg/bundle/manager_test.go
I like the mock and given methods up top so they don't get lost in the actual test code. This also has a couple other little clean-ups, but no real code changes.
=> Move mock functions to top

generatebundlefile/hack/release-public.sh
Was using a relative path, so failed on the new ORAS auth function.
=> Fixing path on profile configfile

generatebundlefile/hack/release-public.sh
aws ecr-public describe-registries wasn't using the release profile.
=> Another tweak for release script

pkg/authenticator/helmsecret.go, pkg/authenticator/helmsecret_test.go
These tests fail sometimes because they conflict
=> Parallel authentication tests conflict

main.go
When I was removing the packagecontroller_controller.go, I must have removed this call on accident.
=> Reactivate the package controller

controllers/package_controller.go, controllers/package_controller_test.go
I noticed a problem deleting a package outside of our namespace caused it to requeue forever. It is just easier to completely ignore forever resources out of our namespace.
=> Ignore all packages outside of namespace

controllers/package_controller.go, controllers/package_controller_test.go
I was very confused why my package wasn't installing and I was just looking at the logs instead of the status.
```
1.656686978400248e+09	INFO	Package.Package	Package bogus-hello-eks-anywhere@latest is not in the active bundle (v1-21-32)
```
I also reduced the status to just the facts, leave the rest for a troubleshooting document
=> Log bogus package name

generatebundlefile/Makefile
=> Removing go compat now we're on GO 1.17

generatebundlefile/bundle.go, generatebundlefile/bundle_test.go, generatebundlefile/data/input_local.yaml, generatebundlefile/ecr.go, generatebundlefile/ecr_helper.go, generatebundlefile/ecr_public.go, generatebundlefile/go.mod, generatebundlefile/go.sum, generatebundlefile/input.go, generatebundlefile/main.go
Added support for writing bundles from ECR private.
In addition moved any functions dealing with GO SDK ecr or ecrpublic imagedetails, to shared function using a common data type. This is a step towards creating shared functions between ECR and ECRpublic, but didn't want the PR to be any bigger than needed so re-factored functions needed for this feature.
=> Private-bundle support

api/v1alpha1/packagebundle_types.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go
Change this state name to something generic so we can avoid future crd changes
=> Use generic invalid bundle state

api/v1alpha1/packagebundlecontroller.go, api/v1alpha1/packagebundlecontroller_test.go, api/v1alpha1/packagebundlecontroller_types.go, pkg/bundle/manager.go
Our standard is to put code in the file without `_type` in the name.
Also, I found the name BaseRef a bit confusing.
=> Move method out of generated code

Makefile
Build tooling uses helm/build, so helm-build target I never remember
=> add helm/build target to match build tooling

Makefile
This avoids the expectation that GOBIN is in your PATH
github actions failed for https://github.com/aws/eks-anywhere-packages/pull/361 so I created this new PR
=> Use full path for setup-envtest

api/v1alpha1/packagebundlecontroller_types.go, charts/eks-anywhere-packages/crds/crd.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml, pkg/bundle/client.go, pkg/bundle/mocks/client.go, pkg/packages/manager.go, pkg/packages/manager_test.go
Currently, we use the registry for the bundle to install every package so that we can support private registries. This works for now since we currently only support everything from public ecr or a private registry. This change allows us to support:
1. private registries
2. sourceRegistry specified in the package custom resource
3. registry specified in the bundle
4. default registry will be the source registry of the bundle if nothing else is specified.
=> Private registry

pkg/packages/manager.go, pkg/packages/manager_test.go
If nothing else is set, use our default gated private registry
=> Use default gated registry for installation

api/v1alpha1/packagebundlecontroller.go, api/v1alpha1/packagebundlecontroller_types.go, pkg/bundle/client.go, pkg/bundle/client_test.go, pkg/packages/manager.go
The active bundle getter was overriding registry in the bundle with one of two values that are always going to be public ECR. This change is the minimal change to get gated packages working so we pull the images from private and the helm charts from public
=> Add default registries

api/v1alpha1/packagebundle.go, api/v1alpha1/packagebundlecontroller.go, api/v1alpha1/packagebundlecontroller_test.go, api/v1alpha1/packagebundlecontroller_types.go, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml, controllers/package_controller.go, controllers/package_controller_test.go, pkg/bundle/client_test.go, pkg/bundle/manager.go, pkg/driver/helmdriver.go
A development friend change so we can use something other than our private registry. This configuration would return us to a current configuration for example:
```
apiVersion: packages.eks.amazonaws.com/v1alpha1
kind: PackageBundleController
metadata:
name: eksa-packages-bundle-controller
namespace: eksa-packages
spec:
defaultRegistry: public.ecr.aws/eks-anywhere
defaultImageRegistry: public.ecr.aws/eks-anywhere
source:
registry: public.ecr.aws/eks-anywhere
repository: eks-anywhere-packages-bundles
```
=> Add default registry

generatebundlefile/ecr_helper.go
Failure on lookup from ECR where some images get tags overridden, and have a tag length of 0.
=> Tag length check failing release script

charts/eks-anywhere-packages/templates/configmap.yaml, ecrtokenrefresher/cmd/ecr-token-refresher/main.go, ecrtokenrefresher/pkg/kubernetes/kubernetes.go
Short term workaround to add emissary-system to config map so that ecrtokenrefresher to always updates that namespace. Also removed failure in case namespace secret couldn't be updated in case emissary was not installed to not trigger unnecessary cronjob runs.
=> Short term workaround for Emissary Hardcoded namespace

generatebundlefile/Makefile, generatebundlefile/go.sum, generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release.sh
This upgrades our oras cli to 0.13.0 which adds the --password-stdin flag to the push and pull commands, which in turn allows us to simplify our authentication with oras.
=> generatebundlefile: update oras to 0.13.0.

api/v1alpha1/packagebundlecontroller_types.go, charts/eks-anywhere-packages/crds/crd.yaml, charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml
A a default to devaultRegistry and remove the entries from the helm chart that were only supposed to work before GA
=> Add default to defaultRegistry

api/v1alpha1/packagebundle.go, api/v1alpha1/packagebundle_test.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/registry_client.go, pkg/webhook/packagebundlecontroller_webhook.go, pkg/webhook/packagebundlecontroller_webhook_test.go
With all these kubeVersion changes lately, it got borked and I guess I didn't notice because I had a bundle. This fixes the latest bundle call for the package controller without breaking the usage for the CLI. I also tried to clean up kubeVersion handling in general and avoid things like make it a string and then parse the string.
=>  Fix kube version again

generatebundlefile/Makefile, generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh
This is issue actively blocking pipelines.
Oras 13 is not working correctly, and blocking pipeline. 
Link to [issue](https://github.com/oras-project/oras/issues/456#issuecomment-1195531498
), and comment from maintainers.
```
As a registry client, ORAS should do the layer pushing in two step:
Try to initiate an upload process via a POST request
Do the blob upload via PUT or PATCHes
During PUT(step 2), ORAS fails to reuse the token obtained by POST(step 1) and ends in rewinding the request body.
Why it only fails for ECR:
An credential cache was introduced in oras-go v2. The cache was keyed by the scopes in the oauth challenge. An OCI-compliant format of the scope should be like …
```
=> Downgrade oras version due to ECR bug.

api/v1alpha1/packagebundle_types.go, api/v1alpha1/packagebundle_webhook.go, pkg/driver/helmdriver_test.go
The `make lint` target complains about these minor issues. I'd rather not see it.
=> Comply with higher level linting

generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh
Older versions of oras don't support --password-stdin, so we have to perform a
separate login action before we push things.
=> generatebundlefile: More work to revert back to older oras

ecrtokenrefresher/pkg/aws/aws.go
Use default registry account for authorization token instead of the default registry associated with the authenticating AWS account.
=> Use default registry instead of default account for authorization token

pkg/authenticator/authenticator.go, pkg/authenticator/ecrsecret.go, pkg/authenticator/ecrsecret_test.go, pkg/driver/helmdriver.go
Create secret in namespace through API instead of relying on helm charts. Address issue that occurs when multiple packages are installed in the same namespace causing issues with helm driver.
Also adding in remove namespace from config map when uninstalling
=> Creating Secret in namespace via API instead of Helm Chart

ecrtokenrefresher/cmd/ecr-token-refresher/main.go
Switching to warning instead of error in print message when missing namespace (mostly due to emissary-system)
=> Switching to Warning Logger for Refresher when missing namespace

generatebundlefile/.gitignore, generatebundlefile/hack/release.sh
When we changed the auth flow with recent ORAS changes, it messed up the flow of writing bundles with multiple kube versions. This should fix the for prod, it's not an issue for dev bundles with the way it's currently done.
=> Kubeversion fix when writing bundles

controllers/packagebundlecontroller_controller.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go
Upon cluster startup, the package bundle controller finds itself without a
bundle. So it reaches out the registry, and tries to create and activate the
newest bundle the registry has. If the package bundle validating webhook has
not yet come online (indicated by a connection refused error), then this code
will requeue a reconcile request for just a short time, so things aren't held
up for hours.
=> package bundle controller: requeue quickly if webhook offline

charts/eks-anywhere-packages/templates/cronjob.yaml
Fixing issue that batch v1 is not part of kubernetes 1.20 and instead needs batch v1beta1
=> Cronjob needs v1beta1 for Kubernetes 1.20

Makefile, hack/helm.sh
Move `helm-docs` under `helm/build` make target directly. This is to help create a separate `helm/package` make target, which will be called by `make presubmit`.
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/365
*Description of changes:* create a new `helm/package` target; `helm/build` won't be impacted.
=> Update helm-docs location

Makefile
Once you modify a file, the make never works again now. Change it so the default target is just like presubmit, but doesn't expect no git diffs.
=> Change the default make target

generatebundlefile/hack/release.sh
Had missed this during the GA, but for the image copy source we should be using this new release file, and not a Dev bundle file for copying over images pinned to a helm version.
=> fixing image copy source file

controllers/package_controller.go, controllers/packagebundle_controller.go
Log names were showing up duplicated, so this change makes it
```
1.6625157014696069e+09	LEVEL(-6)	PackageBundle	Reconcile:	{"bundle": "eksa-packages/v1-21-70"}
```
with PackageBundle instead of PackageBundle.PackageBundle
=> Clean up log name a bit

Makefile
I like to run `make uninstall install run` to get a clean slate with functionally testing and if I don't have anything installed, this fails. This change makes it work every time.
=> Make uninstall idempotent

pkg/driver/helmdriver.go
…on failed package installs
*Issue #473 *
Should prevent us from hitting the resource limit while still giving us some history on failed installs. The previous implementation used the default which keeps all the history.
=> Limiting Helmdriver Upgrade History to address OOMKill

charts/eks-anywhere-packages/templates/deployment.yaml, pkg/packages/manager.go
Do not use kubeconfig for self managed cluster. This fixes docker clusters for example that cannot access their apiserver with the IP in the kubeconfig.
=> Do no use kubeconfig for self

generatebundlefile/.gitignore, generatebundlefile/README.md, generatebundlefile/ecr.go, generatebundlefile/ecr_public.go, generatebundlefile/main.go, generatebundlefile/promote.go
Named version support was never added for the profile commands, and it always defaulted to looking up the latest and messing up the private-profile run since it's calling this file https://github.com/aws/eks-anywhere-packages/blob/main/generatebundlefile/data/input_release.yaml.  
Noticed this issue the new `hello-eks-anywhere` changes recently.
=> Named version for profile commands, and better docs

pkg/bundle/client.go, pkg/bundle/client_test.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/client.go, pkg/bundle/mocks/manager.go
The get bundle list method needs to be a bit more selective for remote management (by k8s version), so this takes it one baby step by combining the get with the sort.
=> Move sort into bundle list

generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_123.yaml
Epic: https://github.com/aws/eks-anywhere/issues/3186
Ties autoscaler to specific helm chart versions for each version of kubernetes.
=> Use K8s-Specific Cluster Autoscaler Versions

generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_123.yaml
Reverts aws/eks-anywhere-packages#499
This broke bundle generation because the necessary tags are missing from the public ECR due to an issue with the promotion job that moves things from private to public ECR. Reverting for now while we fix it.
=> Revert "Use K8s-Specific Cluster Autoscaler Versions"

api/v1alpha1/package.go, controllers/package_controller.go, controllers/package_controller_test.go, controllers/packagebundle_controller.go, controllers/packagebundle_controller_test.go, pkg/bundle/client.go, pkg/bundle/client_test.go, pkg/bundle/mocks/client.go, pkg/packages/manager.go, pkg/webhook/package_webhook.go
Get a PBC for a specific cluster
* Pass clusterName to the get PBC method
* Do not use kubeadmcontrolplane
* Get active bundle based on PBC for the cluster
* Do not reconcile activeBundle delete on bundle reconciliation
=> Handle get PBC and active bundle

ecrtokenrefresher/cmd/ecr-token-refresher/main.go, ecrtokenrefresher/go.mod, ecrtokenrefresher/go.sum, ecrtokenrefresher/pkg/kubernetes/kubernetes.go, ecrtokenrefresher/pkg/kubernetes/kubernetes_test.go
Updating ecr-token-refresher to look for workload clusters via parsing namespaces. Token push was also updated to target each of the workload clusters using a kubeconfig via a secret.
=> Updating ecrtokenrefresher to support updating secret on workload clusters

api/v1alpha1/packagebundlecontroller.go, api/v1alpha1/packagebundlecontroller_test.go, controllers/packagebundle_controller.go, pkg/bundle/client.go, pkg/bundle/client_test.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/client.go
Move the active bundle download to PBC reconciliation
The reason for the move is if we were to reconcile on a deleted bundle, we'd have to iterate through all the PBCs to find out if it was an active bundle. That is possible, but I'd sooner the dependency went one way PBC knows about bundles, but bundles don't know necessarily about PBCs.
=> Move active bundle download

api/testdata/package_webhook_bundle_controller.yaml, api/testdata/packagebundlecontroller.yaml, api/v1alpha1/package.go, api/v1alpha1/packagebundlecontroller.go, api/v1alpha1/packagebundlecontroller_test.go, charts/eks-anywhere-packages/values.yaml, controllers/packagebundlecontroller_controller_test.go, pkg/bundle/client_test.go, pkg/bundle/manager_test.go
During our beta, the only PBC name that was supproted was `eksa-packages-bundle-controller`, but at GA we created `eksa-package-${clusterName}`. This removes support for PBCs using the old name so people are not confused about what PBC they are using.
=> Remove support for eksa-packages-bundle-controller PBC

pkg/authenticator/ecrsecret.go, pkg/authenticator/ecrsecret_test.go, pkg/bundle/client.go, pkg/bundle/client_test.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/bundle/mocks/client.go
Portion of remote management changes to support the ecr-token-refresher. This change is to create the config maps in the corresponding namespace eksa-packages-${CLUSTER_NAME} so token refresher can push to.
Example if management cluster is named mgmt, we will be creating a configmap in eksa-packages-mgmt which holds the namespaces we need to push ecr-tokens to. Config map would look like this
```
apiVersion: v1
kind: ConfigMap
metadata:
name: ns-secret-name
namespace: eksa-packages-mgmt
data:
eksa-packages-mgmt: eksa-packages-placeholder
emissary-system: emissary-ingress
```
=> Create Configmap in Manager for Remote Management

pkg/authenticator/mocks/target_cluster_client.go, pkg/authenticator/target_cluster_client.go, pkg/bundle/client_test.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go, pkg/driver/helmdriver_test.go
Create the `eksa-packages` namespace on the workload cluster to store helm information.
Couple other things in here:
* test data had the pbc name as "eksa-packages-cluster01" instead of cluster01 which just wasn't realistic
* mock was not up to date and had Init instead of Initialize as a method name
=> Create target namespace

controllers/package_controller.go, pkg/authenticator/ecrsecret.go, pkg/authenticator/ecrsecret_test.go, pkg/driver/helmdriver.go
To support updating ecr-token on remote clusters an instance of the cronjob is triggered. 
Two instances of the job are called. The first is to get the ecr-token into the namespaces before an install occurs so that the pods do not back off. A second instance is called to cover namespaces that are created via the helm charts.
Removed nsReleaseMap from ecrsecret as its no longer being used as the job handles keeping track of namespaces. Changed to accept config over rest client as corev1 path are not compatible with batchv1.
=> Trigger Job when installing packages before and after install.

api/v1alpha1/package.go, pkg/webhook/package_webhook.go
If a package is intended to only be installed on a workload cluster, deny request if a custom resource is created with intention of installing in management cluster.
=> Feature cert manager changes

generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_123.yaml, generatebundlefile/data/metrics-server/input_promote.yaml
Bump metrics-server versions due to EKS-D release.
=> Bump metrics-server Versions

generatebundlefile/data/input_120.yaml, generatebundlefile/data/input_121.yaml, generatebundlefile/data/input_122.yaml, generatebundlefile/data/input_123.yaml
`/` is invalid in Metadata name.
=> rename crds to metallb-crds

generatebundlefile/ecr_helper.go, generatebundlefile/main.go
If the depends field in the requires.yaml is an empty string we don't want it in the bundle.
=> Remove empty strings from depends fields

generatebundlefile/data/metrics-server/input_promote.yaml
Because we reverted EKS-D 1.21 images from 1.21.19 to 1.21.18 we are failing to promote the *newer* 1.21.18 charts into the public ECR.
=> Promote Newest 1.21.18 metrics-server Chart

generatebundlefile/data/input_release.yaml
Epic: https://github.com/aws/eks-anywhere/issues/3187, https://github.com/aws/eks-anywhere/issues/3186
Updates the helm charts promoted to production accounts to point at new charts with bug fixes.
=> Update metrics-server and cluster-autoscaler helm chart tags

generatebundlefile/data/input_release.yaml
Try removing latest from tags to get image promo job running.
=> Remove -latest From CA & MS Tags

generatebundlefile/data/input_release.yaml
Trying to get cluster autoscaler helm charts and images promoted
=> Update to 5516 helm chart for image promo

generatebundlefile/data/input_120_prod.yaml, generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml
- Add cert manager to prod bundle.
=> Add cert manager to prod bundle

generatebundlefile/data/input_121_prod.yaml, generatebundlefile/data/input_122_prod.yaml, generatebundlefile/data/input_123_prod.yaml
Epic: https://github.com/aws/eks-anywhere/issues/3187
Ticket: https://github.com/aws/eks-anywhere/issues/3727
Adds metrics-server to production bundle.
I've generated bundles locally using the charts published to `eks-anywhere/metrics-server/charts/metrics-server` and verified they install and run correctly.
=> Add metrics-server Charts to Prod Bundle

Makefile
Old version of gci does not support generics.
=> Update to gci v0.8.0

pkg/bundle/manager.go
The bundle is pretty much a static object because of the signature, so copying the entire thing is kind of a waste. We do nothing to reconcile any valid updates to the bundle anyway right now and we could add the copy back if we do. Either way, the package reconciliation should detect changes to the bundle if there were any. The relationship between the objects is that the bundle doesn't know about the others.
=> Remove deep copy from bundle

Makefile
We were getting these warnings
```
ld: warning: -no_pie is deprecated when targeting new OS versions
```
The other thing though is there is no evidence it actually runs some of those tests. This change stops the warning and I definitely see the tests running now
=> Add build option to test to suppress warning

charts/eks-anywhere-packages/templates/_helpers.tpl, charts/eks-anywhere-packages/templates/cronjob.yaml, charts/eks-anywhere-packages/templates/deployment.yaml
Changing template for controller/cronjob to use chart.yaml version value to create image url
Addresses issue where image tag doesn't exist. Currently release process updates the version in chart.yaml. This PR changes the chart to use that version to build the image url.
This should be a short-term fix until a different solution is developed to handle pulling by tag and promotion.
=> Chart.yaml version for image tag

api/v1alpha1/packagebundlecontroller_types.go, charts/eks-anywhere-packages/crds/crd.yaml, config/crd/bases/packages.eks.amazonaws.com_packagebundlecontrollers.yaml, pkg/driver/helmdriver.go, pkg/driver/mocks/packagedriver.go, pkg/driver/packagedriver.go, pkg/packages/manager.go, pkg/packages/manager_test.go
This PBC setting will tell the controller to create the namespace on the target cluster if it doesn't exist. This is disabled by default because the controller does not impersonate the user applying the package and will always have namespace creation permissions.
Fixes #601
=> Add createNamespace PBC setting

pkg/driver/helmdriver.go, pkg/driver/helmdriver_test.go
The helm chart was installed and the helm secret was in eksa-packages namespace. When that namespace was deleted, it lost the helm state, but the chart resources are still there. When I reinstalled the package, I get:
```
eksa-packages-billy   package.packages.eks.amazonaws.com/my-other-hello   hello-eks-anywhere   23h   installed   0.1.2-latest-helm   0.1.2-latest-helm (latest)   installation not found "my-other-hello": release: not found
```
Closes: https://github.com/aws/eks-anywhere-packages/issues/621
=> Fix installed package problem

generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release_staging.sh
Remove the metadata.Annotations and metadata.Name field before doing the diff check on the bundle files.
Tested locally using a builder-base image, and works. Applying change to Dev and Staging first to verify.
=> Fixing the bundle diff check removing unique metadata fields

Dockerfile, charts/eks-anywhere-packages/templates/deployment.yaml
Missed the deployment `package-manager` command change until I functionally tested it
=> Use the package-manager command everywhere

generatebundlefile/main.go
=> Fix to use the correct env var in release pipelines on region check

generatebundlefile/hack/release_staging.sh
#658
The last region check was calling on the staging account for helm charts, we need to move it earlier to query vs the Account which the images live in.
=> Moving region check call to correct spot

generatebundlefile/data/bundles_staging/1-21.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/staging_artifact_move.yaml
We have a newer version of harbor in production gallery, we should use that since the image replication has already occurred on this one. https://gallery.ecr.aws/eks-anywhere/harbor/harbor-helm
=> Updating helm chart to newer version

generatebundlefile/bundle_types.go
We don't generate deepcopy for any other resources except for this one for some reason. This stops generating the deepcopy for this resource.
=> Do not generate deepcopy for generate bundle file

cmd/server.go
These scaffolding markers are for kubebuilder, but it only reads main.go. We are unlikely to use scaffolding this way going forward.
=> Remove unused scaffolding markers

controllers/package_controller.go, controllers/packagebundle_controller.go, controllers/packagebundlecontroller_controller.go, pkg/bundle/client.go, pkg/bundle/client_test.go, pkg/webhook/package_webhook.go, pkg/webhook/packagebundle_webhook.go
This is a simple rename of bundleClient to managerClient. This was talked about a while back that our two main clients would be the TargetClusterClient and ManagerClient depending on who you needed to talk to.
=> Rename bundle client to manager client

generatebundlefile/data/bundles_dev/1-25.yaml
Removes duplicate autoscaler entry in 1-24 as well.
Prep for 1.25 testing
Adds support for 1.25 packages
=> Add 1-25 Dev Bundle Support

generatebundlefile/bundle_test.go, generatebundlefile/ecr.go, generatebundlefile/ecr_public.go
The tag 
`9.21.0-1.21-56810429df35d3ec6ddd5b83ce409f1f33d76c1b-latest-helm`
Was breaking the logic since it contained "latest", but didn't end in latest. Fixed the statement, and added a test to check for tags like this going forward.
=> Allowing tags to contain latest in the middle and still work

Makefile
The generatebundle command causes controller-gen to generate the file `config/crd/bases/_.yaml` since the generate bundle uses  kubebuilder style structs. This stops the generation of that useless file.
=> Reduce path for controller-gen

pkg/artifacts/registry.go
This used to be true, but at some point the RegistryPuller became a general purpose registry puller.
=> Removes inaccurate comment.

pkg/artifacts/registry.go, pkg/registry/artifact.go, pkg/registry/artifact_test.go
By moving SetURI to ParseArtifactFromURI we re-use commonly used terminology and semantics around the term "Parse", which implies that the process can fail (returning nil and an error), as opposed to the SetURI, which left it up to the caller to initialize the Artifact, and abort if the SetURI call failed.
Also adds some tests for the parsing algorithm, and changes methods to remove the pointer receiver which better communicates that the methods are read-only.
=> Rework SetURI into ParseArtifactFromURI

pkg/artifacts/registry.go, pkg/registry/client_test.go, pkg/registry/credentials.go, pkg/registry/credentials_test.go, pkg/registry/storage.go
Two smallish changes:
Lift configfile.ConfigFile out of CredentialsStore
Rather than assuming that users of CredentialStore will know to call Init
after instantiation, the CredentialStore's dependency on a Docker *ConfigFile
is made explicit by requiring it to be passed to the constructor. Now we need
never worry that a user will forget to call Init, and it removes the awkward
pattern of New-then-Init.
and:
Don't store the RegistryPuller's StorageClient
There's no point in storing it, as it's never reused.
=> Lift configfile

pkg/artifacts/registry.go, pkg/registry/client_test.go, pkg/registry/credentials.go, pkg/registry/credentials_test.go, pkg/registry/storage.go
This reverts commit 360d2998571ed9bf08029afcb2c8dd7b198f5113.
The reversion of de9c0be (by 360d299) was performed due to what was believed to be a regression, but was later found to be a config issue.
Since 360d299 squashed both the revert, plus another small change into one commit, this revert will undo both. That is, it re-instates de9c0be, and reverts the small change squashed into the original revert. (Clear as mud, right?)
A follow up commit will manually re-instate the small change.
=> Revert "Revert (#761)"

generatebundlefile/ecr_helper.go, generatebundlefile/hack/promote.sh, generatebundlefile/main.go, generatebundlefile/options.go, generatebundlefile/promote.go
Why this needs to exist is because there is two sets of dev build being produced, one by the EKS-A pipeline using Git Tag, and another by the new dev pipeline. The current logic just defaults to latest, so adding a tag option allows us to always promote our dev builds for e2e purposes to always use dev chart.
=> Add tag option for package controller dev promote pipeline

charts/eks-anywhere-packages/templates/service.yaml
*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/780
=> Fix controller service targetPort

generatebundlefile/ecr.go, generatebundlefile/ecr_test.go, generatebundlefile/promote.go
When promoting images, some images are doubletagged, and this will help ensure it preserves the correct tag during the copy command that was specified by the promote command.
ecr-token-refresher has tags `0.0.0-abc` and `release-0.14`.
If we use promote with substring match for `0.0.0` we want to return that tag back to the copy command, and not the `release-0.14` one since both get returned by the sdk query.
=> Adding priority to tag substring promote cmd

generatebundlefile/data/bundles_dev/1-21.yaml, generatebundlefile/data/bundles_dev/1-22.yaml, generatebundlefile/data/bundles_dev/1-23.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/bundles_dev/1-25.yaml
Previously, because eks-d specified a release patch number and it was included in the promo data config file, charts would stop updating as soon as eks-d published a new patch.
Also starts pulling in charts using the 0.6.2 image.
=> Allow metrics-server To Auto Update in Dev Bundle

charts/eks-anywhere-packages/templates/deployment.yaml, pkg/artifacts/registry.go, pkg/driver/helmdriver.go, pkg/registry/certificates.go, pkg/registry/credentials.go
Add support for cluster specific configuration:
* cluster specific ca.crt file
* cluster specific insecure file
* cluster specific credentials config.json file
The existence of the insecure file indicates insecure mode.
=> Support cluster specific ca.crt and insecure

charts/eks-anywhere-packages/templates/configmap.yaml, charts/eks-anywhere-packages/values.yaml
The `ns-secret-map` configMap in `eksa-packages` namespace is no longer needed as package controller is now responsible for creating that in the target namespace in form of `eksa-packages-[clusterName]` (https://github.com/aws/eks-anywhere-packages/blob/main/pkg/bundle/client.go#L162). We are no longer supporting for package installation in `eksa-packages` namespace.
=> Remove unused configmap

generatebundlefile/hack/common.sh
In case a new bundle exist, just create an empty file for comparison so the new bundle will always get pushed.
=> Fix when new version bundle doesn't exist yet

generatebundlefile/promote.go
Used the wrong client in the function I created last week for cross-account releases.
=> Fixing typo from source AccountID function

generatebundlefile/data/staging_artifact_move.yaml
The function is looking for images in the Private ECR, but the chart in the Public ECR since it's mimicking the behavior of our other packages. Due to this we can't use the Core teams tags since those are only written into public, but not in Private ECR.
=> Moving to dev tag for packages image move

charts/eks-anywhere-packages/templates/role.yaml, charts/eks-anywhere-packages/templates/rolebinding.yaml
These permissions will allow the eksa-controller to delete package bundle controller helm installations completely, and without error.
The namespace in question is the workload clusters, e.g. eksa-packages-my-workload-cluster.
The secret in question is the registry-mirror-secret that is created for workload clusters (regardless of whether or registry mirror is in use).
Part of https://github.com/aws/eks-anywhere-packages/issues/807.
=> Allow eksa-controller-manager to remove package bundle controllers

charts/eks-anywhere-packages/templates/namespace.yaml
This will fail without https://github.com/aws/eks-anywhere-packages/pull/835 as it creates the cluster namespaces in the chart.
=> Add more compatibility cases for helm chart namespace

generatebundlefile/data/promote/eks-anywhere-packages/promote.yaml, generatebundlefile/hack/promote.sh
When we added a promote file for the Package controller as a package, it didn't include the `copy-images` flag which is needed for the e2e dev chart to have it's image in the public ECR. Adding it back here.
=> Copying images over for packages dev chart for e2e

controllers/packagebundlecontroller_controller.go
Several errors happened during start-up and none of them matched the "connection refused", but they did result in a one hour timer for the PBC.
=> Avoid one hour wait for pbc

charts/eks-anywhere-packages-migrations/templates/adopt-crds-awssecret.yaml
Add pull secret to migrations since the sourceRegistry set by the controller points to private ECR. This might change soon by passing values down to dependencies but having it available is still a good thing.
=> Add image pull secrets to migrations

credentialproviderpackage/cmd/aws-credential-provider/main.go, credentialproviderpackage/go.mod, credentialproviderpackage/internal/test/files.go, credentialproviderpackage/pkg/configurator/bottlerocket/bottlerocket.go, credentialproviderpackage/pkg/configurator/bottlerocket/bottlerocket_test.go, credentialproviderpackage/pkg/configurator/configurator.go, credentialproviderpackage/pkg/configurator/linux/linux.go, credentialproviderpackage/pkg/configurator/linux/linux_test.go, credentialproviderpackage/pkg/filewriter/tmp_writer_test.go, credentialproviderpackage/pkg/filewriter/writer_test.go, credentialproviderpackage/pkg/templater/partialyaml_test.go, credentialproviderpackage/pkg/templater/templater.go, credentialproviderpackage/pkg/templater/templater_test.go
Changing the module to match rest of repository. Also needed for build-tooling to properly generate the license
=> Changing module credential-provider to github.com/aws/eks-anywhere-packages/credentialproviderpackage

generatebundlefile/data/staging_artifact_move.yaml
This versions.name value controls what eks-anywhere-packages images get copied over to the ECR image scanning account. In order to mirror prod images, we should copy over v0.x.xx-latest series. This version needs to match the latest release branch tag (i.e. https://github.com/aws/eks-anywhere-build-tooling/blob/release-0.14/projects/aws/eks-anywhere-packages/GIT_TAG).
=> Update eks-anywhere-packages versions

generatebundlefile/data/staging_artifact_move.yaml
We should use the helm tag, instead of the image tag. Verified this helm tag exists in the dev repo.
=> Fix eks-anywhere-packages versions for image scanning

credentialproviderpackage/charts/credential-provider-package/values.yaml
Changing digets value name in credential-package so build tooling can properly substitute
=> Fixing digest for credential package

generatebundlefile/data/staging_artifact_move.yaml
0.2.30 series tag is inconsistent between private and public registries, causing the helm chart promotion logic to fail. Revert this change before we resolve this inconsistency issue.
=> Revert Update eks-anywhere-packages versions for image scanning

charts/eks-anywhere-packages/templates/_helpers.tpl, charts/eks-anywhere-packages/templates/credentialpackage.yaml, charts/eks-anywhere-packages/templates/cronjob.yaml
Currently there is a bug where Bottlerocket 1.25 k8s versions (as of BR version 0.12.0) and greater inaccurately renders the KubeletCredentialProvider causing the node to crash. Adding the ability for the helm chart to revert back to the cronjob in cases where the credential-package will not work.
* In cases where the aws-secret does not exist and the values are not set in the chart, neither the credential-package or cronjob will be enabled
* In the case where the workload cluster is not compatible the chart will check if the cronjob is already enabled if not it will re-enable even if mgmt cluster users credential package.
* Also versions of BR < 1.11.0 does not expose the necessary APIs for the credential package thus the cronjob will be enabled.
* If cronjob.suspend is set to false then …
=> Determining cluster compatability with credential package

charts/eks-anywhere-packages/templates/cronjob.yaml
The rendering of the cronjob is still triggured by looking at this value vial the template function lookup-credential.method. This just fixes the case where we need to turn on the cronjob because the credential-package is not compatiable.
=> Set cronjob suspend to false when cronjob is rendered.

charts/eks-anywhere-packages/templates/_helpers.tpl, pkg/authenticator/target_cluster_client.go, pkg/bundle/manager.go, pkg/bundle/manager_test.go
BR v1.13 was released and does not include the fix needed for credential package to work so logic was updated.
Removing the need to copy annotations for secret over as secret is no longer reapplied on management cluster.
=> Change secret to not be reapply on management cluster. Update BR versions

charts/eks-anywhere-packages/templates/_helpers.tpl, charts/eks-anywhere-packages/templates/awssecret.yaml, charts/eks-anywhere-packages/templates/certs.yaml, charts/eks-anywhere-packages/templates/clusterrole.yaml, charts/eks-anywhere-packages/templates/clusterrolebinding.yaml, charts/eks-anywhere-packages/templates/configmap.yaml, charts/eks-anywhere-packages/templates/credentialpackage.yaml, charts/eks-anywhere-packages/templates/cronjob.yaml, charts/eks-anywhere-packages/templates/deployment.yaml, charts/eks-anywhere-packages/templates/namespace.yaml, charts/eks-anywhere-packages/templates/network-policy.yaml, charts/eks-anywhere-packages/templates/package.yaml, charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml, charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml, charts/eks-anywhere-packages/templates/role.yaml, charts/eks-anywhere-packages/templates/rolebinding.yaml, charts/eks-anywhere-packages/templates/service.yaml, charts/eks-anywhere-packages/templates/serviceaccount.yaml, charts/eks-anywhere-packages/templates/servicemonitor.yaml, charts/eks-anywhere-packages/templates/webhook.yaml, charts/eks-anywhere-packages/values.yaml
*Description of changes:* Add support for only rendering a package resource as a temporary workaround until that's generated by the eksa controller.
/hold until I review it tomorrow
=> Add support for rendering just a package

charts/eks-anywhere-packages/templates/_helpers.tpl, charts/eks-anywhere-packages/templates/credentialpackage.yaml, credentialproviderpackage/go.mod, credentialproviderpackage/go.sum, credentialproviderpackage/pkg/configurator/bottlerocket/bottlerocket.go, credentialproviderpackage/pkg/configurator/bottlerocket/bottlerocket_test.go
* Added CP toleration as default for credential package
* Add version check to configurator binary to prevent node breakage
* Defaulting to cronjob for BR regardless of k8s version for BR < 1.13 by default
=> Control Plane Toleration and Bottlerocket version check

generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/staging_artifact_move.yaml
The tags used in the staging bundles were not the ones from Public ECR so it was failing staging pipeline.
=> Using the actual tags for metallb from public ECR

generatebundlefile/data/bundles_dev/1-22.yaml, generatebundlefile/data/bundles_dev/1-23.yaml, generatebundlefile/data/bundles_dev/1-24.yaml, generatebundlefile/data/bundles_dev/1-25.yaml, generatebundlefile/data/bundles_dev/1-26.yaml, generatebundlefile/data/bundles_staging/1-22.yaml, generatebundlefile/data/bundles_staging/1-23.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/staging_artifact_move.yaml
* Moved packages,crds,migrations, and credential package under aws org for dev
* Updated staging move with latest helm chart
* Added packages,crd,migrations, and credential package to staging bundle.
=> Updating staging bundles in prep for 0.15 release.

generatebundlefile/bundle.go, generatebundlefile/bundle_test.go, generatebundlefile/ecr_public.go, generatebundlefile/hack/release_staging.sh, generatebundlefile/main.go, generatebundlefile/sts.go
on the ECR Public `DescribeImagesInput` function there was this note.
```
// The AWS account ID associated with the public registry that contains the
// repository in which to describe images. If you do not specify a registry, the
// default public registry is assumed.
RegistryId *string
```
What this effectively doing was looking up the bundle source of the helm charts in the source ECR public account to find the image sha. We hadn't noticed this issue previously since the images tags were identical between dev and staging, but we see the issue now on the EKS-A tagged artifacts since the tag is not the same between dev/staging.
This fix will source the correct Destination accountID when looking up artifacts for the bundle.
=> Fixing Ecr public lookup not use default accountID registry

generatebundlefile/data/prod_artifact_move.yaml
For the first release we don't want to move any other helm charts than the EKS-A release bundle version (Which already exists) for packages into the prod ECR repo as it's confusing to a user. 
We will un-comment this once we have newer versions we want to update later on.
=> Commenting out packages for artifact-move

credentialproviderpackage/charts/credential-provider-package/templates/daemonset.yaml, credentialproviderpackage/pkg/configurator/linux/linux.go, credentialproviderpackage/pkg/configurator/linux/linux_test.go, credentialproviderpackage/pkg/configurator/linux/templates/credential-provider-config.yaml, credentialproviderpackage/pkg/configurator/linux/testdata/expected-config-alpha.yaml, credentialproviderpackage/pkg/configurator/linux/testdata/expected-config-beta.yaml, credentialproviderpackage/pkg/configurator/linux/testdata/expected-config.yaml
Have credential-provider-config api version be dynamically generated based on kubernetes version.
Kubernetes added v1 support for kubelet.config.k8s.io and credentialprovider.kubelet.k8s.io in v1.26 and will be removing v1alpha1 in future versions. Adding support now before v1.27
Currently this is setup to bump the api version one version after the release supported. For example even though v1 was added to v1.26 we will still use v1beta1. This is because there are cases during an upgrade for example of a rolling upgrade of v1.25 -> v1.26 cluster that the node the helm chart installs on might be v1.26 and try to run the deamonset on the 1.25 nodes with an unsupported api. Since we don't allow a two version jump of k8s version at once this should be fine.
By submitting this pull request, I …
=> Template credential-provider-config api version

generatebundlefile/data/bundles_dev/1-27.yaml, generatebundlefile/data/promote/autoscaler/promote.yaml, generatebundlefile/data/promote/metrics-server/promote.yaml, generatebundlefile/hack/generate_bundle.sh
N/A
Add k1.27 support. Confirmed metrics-server and auto-scaler exists in the l0g8r8j6 account.
=> Add k1.27 support in dev

charts/eks-anywhere-packages/templates/_helpers.tpl
N/A
It appears that customer with BR 1.13.1 is still using CronJob. This change makes BR 1.13.1 use cronJob, and move to credential package on 1.13.2. Currently the logic for k1.25 and other versions are the same, but it's still kept as separate logic  in case we foresee further issues on BR with k1.25.
=> Update credential vs cronjob semverCompare logic

credentialproviderpackage/charts/credential-provider-package/templates/_helpers.tpl, credentialproviderpackage/charts/credential-provider-package/templates/daemonset.yaml
*Issue # *
Adding support for ubuntu 22.04 in credential package.
Ubuntu changed from using /etc/sysconfig/kubelet to /etc/default/kubelet in 22.04. Updating volume mounts on credential package to support this
=> Support for Ubuntu 22.04 in credential package

charts/eks-anywhere-packages-migrations/templates/_helpers.tpl
*Issue #, if available:* After "copy packages" to a registry mirror, images doesn't exist in the registry mirror with tags. 
*Description of changes:* Pull eks-anywhere-packages-migrations images by sha256 instead of tag
=> Pull eks-anywhere-packages-migrations images by sha256

charts/eks-anywhere-packages-migrations/templates/_helpers.tpl, charts/eks-anywhere-packages-migrations/values.yaml, charts/eks-anywhere-packages/values.yaml
*Issue #, if available:* In airgapped environment, registry-mirror needs to host curated packages images. Those images' urls can only be fetched from packageBundle. But packageBundle doesn't store tags information. So registry-mirror will not have tag info as well.
*Description of changes:* eks-anywhere-package helm chart and its dependencies switch to sha256 tag so it can pull images from registry-mirror
=> Adjust eks-anywhere-packages tags to sha256 format

charts/eks-anywhere-packages/values.yaml
*Issue #, if available:* we need to use real tag inside eks-anywhere-packages because some hack during release process depends on it.
=> Use real tag in eks-anywhere-packages

pkg/bundle/manager.go, pkg/bundle/manager_test.go
*Description of changes:* Allow reconciler to be rescheduled, when the secrets is being injected.
=> Allow reconciler retry downloading bundle

charts/eks-anywhere-packages/templates/packagebundlecontroller.yaml
*Issue #, if available:* NA
*Description of changes:* When EKSA create cluster, the cli command waits until the package bundle is available. However, when regional curated packages registry is used, the credential would not be available when the first reconciling is run, but it will be available shortly afterward as the credential injector finished its work. So this waiting period needs to be reduced from 1h to 10s, to make "create cluster" successful.
=> Decrease wait time when pulling bundle failed

OWNERS, credentialproviderpackage/pkg/configurator/linux/linux.go
KubeletCredentialProviders was GA'd in 1.26 and removed as a feature flag in 1.28. Adding the feature flag caused the kubelet to exit on startup when upgrading to a 1.28 cluster. 
The KubeletCredentialProviders is now only added when k8s version is less than v1.26. 
=> Fix Kubelet Args for 1.28

generatebundlefile/promote.go
*Description of changes:* Tag is not reliable when it comes to identify container images. Copy images command thus should take into account of the sha256, to make sure the artifact matching sha256 is really copied instead of an artifact matching tag.
Tested manually e2e
=> Copy image digest as well as tag

generatebundlefile/Makefile, generatebundlefile/hack/docker-ecr-config.json, generatebundlefile/main.go, generatebundlefile/options.go, generatebundlefile/promote.go
Support private ECR-only bundle generation and promotion.
=> Support private ECR-only bundle generation and promotion

generatebundlefile/promote.go
* Make client creation flow use shared config
* ECR and STS clients are created to perform private ECR operations. In the new build flow, both source and release endpoints are private ECR, so we need these release clients too.
=> Add release clients for new build flow

Makefile, generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/main.go, generatebundlefile/options.go, generatebundlefile/promote.go, pkg/signature/manifest.go
The regional builds use a different public key for signing verification, so we need to update that.
Also renaming `NEW_BUILD_MODE` to `REGIONAL_BUILD_MODE` across the board.
=> Update env var and public key for regional builds

generatebundlefile/hack/common.sh
This PR changes the bundle generation script to use a common public key for signing artifacts.
=> Use common public key for signing artifacts

generatebundlefile/bundle_test.go, generatebundlefile/data/bundles_staging/1-24-regional.yaml, generatebundlefile/data/bundles_staging/1-24.yaml, generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/staging_artifact_move.yaml, generatebundlefile/ecr.go, generatebundlefile/ecr_helper.go, generatebundlefile/ecr_public.go, generatebundlefile/ecr_test.go, generatebundlefile/hack/policy.json, generatebundlefile/helm.go, generatebundlefile/main.go, generatebundlefile/options.go, generatebundlefile/promote.go
* Add input files for regional staging package bundle generation 
* Promote `eks-anywhere-packages` (and related artifacts), `ecr-token-refresher`, `credential-provider-package` to public ECR.
=> Add input files for regional staging package bundle generation

generatebundlefile/data/promote/autoscaler/promote.yaml, generatebundlefile/data/promote/metrics-server/promote.yaml
Stop promotion of Kubernetes v1.22 and v1.23 related artifacts for metrics-server and autoscaler since these versions are no longer supported.
=> Stop promotion of Kubernetes v1.22 and v1.23 related artifacts

generatebundlefile/main.go
In regional builds, run promotions always. In non-regional builds, run promotion only if `promote` flag is specified.
=> Fix condition for running promote operation

generatebundlefile/main.go
Stop flow after promotion in case of non-regional build mode. This is how it was previously, until one of the subsequent PRs removed it.
=> Stop flow after promotion in case of non-regional build mode

generatebundlefile/data/bundles_dev/1-25-regional.yaml, generatebundlefile/data/bundles_dev/1-25.yaml, generatebundlefile/data/bundles_dev/1-26-regional.yaml, generatebundlefile/data/bundles_dev/1-26.yaml, generatebundlefile/data/bundles_dev/1-27-regional.yaml, generatebundlefile/data/bundles_dev/1-27.yaml
Promote new metrics-server chart to dev.
https://github.com/aws/eks-anywhere-internal/issues/2042
Promotes new metrics-server version we are building to the dev packages bundle.
=> Bump Metrics Server on Dev

generatebundlefile/data/promote/emissary/promote.yaml
Revert Emissary package back down to 3.6.0
=> Revert emissary to 3.6.0

generatebundlefile/README.md, generatebundlefile/data/bundles_dev/1-29-regional.yaml, generatebundlefile/data/bundles_dev/1-29.yaml, generatebundlefile/data/promote/metrics-server/promote.yaml
Bump metrics-server tag to 0.7.0 for Kubernetes 1.29.
=> Bump metrics-server tag to 0.7.0 for Kubernetes 1.29

generatebundlefile/ecr_public.go
Add logging for ECR Public image SHA lookup.
=> Add logging for ECR Public lookup

generatebundlefile/data/bundles_dev/1-25-regional.yaml, generatebundlefile/data/bundles_dev/1-25.yaml, generatebundlefile/data/bundles_dev/1-26-regional.yaml, generatebundlefile/data/bundles_dev/1-26.yaml, generatebundlefile/data/bundles_dev/1-27-regional.yaml, generatebundlefile/data/bundles_dev/1-27.yaml, generatebundlefile/data/bundles_dev/1-28-regional.yaml, generatebundlefile/data/bundles_dev/1-28.yaml, generatebundlefile/data/promote/metrics-server/promote.yaml
Bump metrics-server tag to 0.7.0 for all Kubernetes versions.
=> Bump metrics-server tag to 0.7.0 for all Kubernetes versions

generatebundlefile/data/bundles_staging/1-25-regional.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29-regional.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml, generatebundlefile/hack/release_staging.sh
* Adding 1.29 staging packages bundle input files.
* Update Helm chart tags to latest for other Kubernetes versions
* Removing 1.24 packages input files.
=> Add Kubernetes 1.29 staging packages bundle files, deprecate 1.24 packages

generatebundlefile/hack/common.sh
Don't export AWS_PROFILE env var during login as it leads to errors like
```
The config profile () could not be found
```
=> Don't export AWS_PROFILE env var during login

Makefile, credentialproviderpackage/Makefile, ecrtokenrefresher/Makefile, generatebundlefile/Makefile, generatebundlefile/ecr_helper.go, generatebundlefile/go.mod, generatebundlefile/go.sum, generatebundlefile/hack/policy.json
We pull ADOT images directly from public ECR in our builds and push to our ECR. In a recent release, ADOT maintainers added an SBOM artifact to their image manifest list (image index) which Skopeo doesn't support (https://github.com/containers/skopeo/issues/2174). So this PR adds the logic for modifying the manifest list to include only the amd64 and arm64 images for the project.
Tested this flow locally and confirmed skopeo copy of the modified manifest works.
=> Remove non-image artifacts from image index

generatebundlefile/data/bundles_prod/1-25-regional.yaml, generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26-regional.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27-regional.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28-regional.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29-regional.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/prod_artifact_move-regional.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml, generatebundlefile/hack/common.sh, generatebundlefile/hack/release_prod.sh
Add Kubernetes 1.29 prod packages input files, deprecate 1.24 prod packages
=> Add Kubernetes 1.29 prod packages bundle files, deprecate 1.24 prod packages

generatebundlefile/data/bundles_prod/1-25.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/prod_artifact_move.yaml, generatebundlefile/data/staging_artifact_move.yaml
Fix prometheus version sha conflict. The helm points to the wrong sha digest for the given tag.
=> fix prometheus version sha conflict

pkg/packages/manager_test.go, pkg/webhook/package_webhook.go, pkg/webhook/packagebundle_webhook.go, pkg/webhook/packagebundle_webhook_test.go, pkg/webhook/packagebundlecontroller_webhook.go
Recently we bumped controller-runtime (CR) from v0.14.4 to v0.16.5. In CR v0.15.0, they added a [change](https://github.com/kubernetes-sigs/controller-runtime/commit/927c09e54313d6476b5780b7f029f381d777c149) which removes logic for the injection of decoders. Hence we need to explicitly initialize the decoders when registering the validating webhook handlers for the packages CRDs.
=> Provide admission webhook decoder when instantiating CRD validators

generatebundlefile/hack/common.sh
Fixes the error
```console
The config profile (default) could not be found
```
=> Fix AWS profile arg for ECR login

charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml
*Issues:*
https://github.com/aws/eks-anywhere/issues/7114
https://github.com/aws/eks-anywhere-internal/issues/2268
The changes to the helm chart conditionally create the registry mirror secret. The values for the secret are inputted from EKS-A when helm installing `eks-anywhere-packages` on a cluster with registry mirror configuration.
But whenever the `eks-anywhere-packages` package was updated; when we have a new active bundle on the PBC we run into a scenario where the values are not found and the secret got empty (as described on the issues above).
The changes now ensure that the helm chart secret is only recreated either 
1. The secret is not found on the cluster
2. There are values to be updated with for the secret
By submitting this pull request, I confirm …
=> Conditionally install registry mirror secret with Helm chart

charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml
Helm has an issue where its not parsing the comment block properly. Similar issues mentioned on this [post](https://stackoverflow.com/a/63383447/13156793). Helm template gives
```yaml
kind: Secret
metadata:
annotations:
```
The `apiVersion: v1` should have been parsed as part of the yaml but its being added to comment.
Moved the comments and ran template to check issue was resolved.
=> Moving helm chart comment block

charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml
*Issue https://github.com/aws/eks-anywhere-internal/issues/2268*
When creating workload clusters from an EKS-A management cluster using the eks-a controller workflow, we have set a flag `workloadPackageOnly` which creates a `eks-anywhere-packages` package object on the cluster. 
This then reconciles and creates the necessary PBC and dependent packages for a workload cluster.
But the `registry-mirror-secret` values are inputted from EKS-A; thereby they were always empty for a workload cluster with registry mirror configured. This fix enables creating the secret for workload cluster during install from EKS-A controller.
=> Adding reg mirror sec creation on flag workloadPackageOnly

api/v1alpha1/packagebundlecontroller.go, api/v1alpha1/packagebundlecontroller_test.go, controllers/packagebundlecontroller_controller.go, controllers/packagebundlecontroller_controller_test.go, pkg/bundle/client.go, pkg/registry/certinjector.go, pkg/registry/certinjector_test.go
*Issue https://github.com/aws/eks-anywhere-internal/issues/2269:*
Packages controller pod has a mounted secret `registry-mirror-cred`. This secret creates the CA cert on the pod with the name `<cluster-name>_ca.crt`.
When dealing with multiple clusters; specifically when workload clusters are created from EKS-A. The packages controller pod fails with an 
```
tls: failed to verify certificate: x509: certificate signed by unknown authority
```
As the new cluster's CA cert is not updated on the mounted secret.
These changes add a step in the PBC controller workflow that checks the mounted secret and updates the registry CA cert if the field is missing in the data.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> Updating registry mirror CA cert in PBC controller reconcile

generatebundlefile/data/staging_artifact_move.yaml
During bumping packages artifacts for staging, the `eks-anywhere-packages-crds/migration` were [missed](https://github.com/aws/eks-anywhere-packages/pull/1111). Updating the images with the same commit tag as other packages artifacts. 
=> Update packages image to point to latest tag

generatebundlefile/data/bundles_staging/1-25.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/staging_artifact_move.yaml
The current tag for `eks-anywhere-packages-migrations` is unavailable on public ecr. Update it to the latest tag that's present in our build account 
=> Fix packages migration chart tag to latest

charts/eks-anywhere-packages/templates/registrymirrorsecret.yaml, ecrtokenrefresher/pkg/secrets/common/common.go
Modified the reg secret logic to always do a lookup on the cluster to ensure backward compatibility since helm keep was not existing in older clusters.
=> Adding secret defaulting and always look up reg secret

generatebundlefile/data/bundles_dev/1-30-regional.yaml, generatebundlefile/data/bundles_dev/1-30.yaml, generatebundlefile/data/promote/autoscaler/promote.yaml, generatebundlefile/data/promote/metrics-server/promote.yaml, generatebundlefile/hack/generate_bundle.sh
Add dev bundles for K8s version 1.30. Update autoscaler and metrics to latest tags on the dev bundle. 
=> Add dev bundles for K8s version 1.30

generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29-regional.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30-regional.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml, generatebundlefile/hack/release_staging.sh
Bump curated packages to their latest build versions and add Kubernetes version 1.30 to staging bundles. Deprecate Kubernetes version 1.25 bundles. 
=> Add Kubernetes 1.30 staging packages bundle and deprecate 1.25

generatebundlefile/data/bundles_dev/1-30-regional.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml
Fix release branch on 1-30 regional bundle to use the right image and fix typo on staging bundles artifact  move files on legacy and regional accounts. 
=> Fix dev and staging bundles using incorrect tags

generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/promote/metallb/promote.yaml, generatebundlefile/data/staging_artifact_move.yaml
Some of the tags updated in the staging bundle weren't present in the Build Account `857151390494` Public ECR from which the staging pipeline copies over to the Packages staging account. This lead to staging pipeline failing for Packages. Additionally, metallb images were still getting promoted for the older tag as we hadn't updated the tag on promote file. This change updates the image tags on staging bundles to the images that have been verified to be present in the above account's public ECR and fixes the tag for metallb to promote the latest version bump. 
=> Fix staging bundle image tags after manually running pipelines

generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/staging_artifact_move.yaml
The metric server images in build account for Kubernetes version 1.27 and above are tagged with suffix `-latest-helm`. Add the suffix to fix build failures on packages staging.
=> Fix metrics server image tags for all Kubernetes versions

generatebundlefile/main.go
The packages promotion code only supported promoting one version for each package in the input file. This PR fixes that to allow more than one version to be promoted.
=> Ensure all versions specified in input file are promoted

generatebundlefile/ecr_helper.go
We want the promoted image tags to be of the format `X.Y.Z-<commit hash>`, for example, `0.4.3-451cb0d2fd416176540b65be9e46b4cfc0db99f0` but sometimes if the same digest has multiple tags, it could pick up an image which does not follow the structure, such as `0.4.3-latest-helm`, as it's just getting the first element from the list without checking its format.
=> Filter out proper image tags based on tag format

generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29-regional.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30-regional.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml
Packages staging bundle release failed as there was a mismatch in commits during the build between the Prometheus images built after this [commit](https://github.com/aws/eks-anywhere-build-tooling/pull/3292) vs the helm charts built later after this [fix](https://github.com/aws/eks-anywhere-build-tooling/pull/3330). Since we only reference the tags for helm charts in our staging bundles, the builds implicitly expect the same tag for the images. Due to the mistmatch on commits the bundle build wasn't able to fetch an appropriate image for that tag. Kicked off a fresh build of Prometheus images and charts, then updated the tags on bundle to reflect the latest image tag.   
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> Fix prometheus image tags in staging

generatebundlefile/data/bundles_staging/1-26-regional.yaml, generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27-regional.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28-regional.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29-regional.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30-regional.yaml, generatebundlefile/data/bundles_staging/1-30.yaml, generatebundlefile/data/staging_artifact_move-regional.yaml, generatebundlefile/data/staging_artifact_move.yaml
The current cert-manager helm-chart is borked in prod as the chart size is too big to be stored as K8s secret by helm. Update the chart after the size issue has been fixed.   
=> Bump cert-manager to fixed chart

generatebundlefile/data/bundles_prod/1-26-regional.yaml, generatebundlefile/data/bundles_prod/1-26.yaml, generatebundlefile/data/bundles_prod/1-27-regional.yaml, generatebundlefile/data/bundles_prod/1-27.yaml, generatebundlefile/data/bundles_prod/1-28-regional.yaml, generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29-regional.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/bundles_prod/1-30-regional.yaml, generatebundlefile/data/bundles_prod/1-30.yaml, generatebundlefile/data/prod_artifact_move-regional.yaml, generatebundlefile/data/prod_artifact_move.yaml
The current cert-manager helm-chart on prod is borked as the chart size is too big to be stored as K8s secret by helm. Update the chart after the size issue has been fixed.
=> Bump cert-manager chart for prod

generatebundlefile/data/promote/autoscaler/promote.yaml, generatebundlefile/data/promote/eks-anywhere-packages/promote.yaml, generatebundlefile/data/promote/emissary/promote.yaml, generatebundlefile/data/promote/metallb/promote.yaml, generatebundlefile/data/promote/metrics-server/promote.yaml
[#2389](https://github.com/aws/eks-anywhere-internal/issues/2389)
Updated private registry for promo job input files to reference the regional beta account private ECR registry as we will only be building from regional pipelines as the source of truth.
=> Update private registry for promote job input files

generatebundlefile/hack/common.sh, generatebundlefile/hack/generate_bundle.sh, generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
Tag package bundles differently for regional staging/prod so that they don't override one another.
=> Tag package bundles differently for regional staging/prod

generatebundlefile/main.go, generatebundlefile/options.go, generatebundlefile/promote.go, pkg/signature/manifest.go, pkg/webhook/packagebundle_webhook_test.go
[#2389](https://github.com/aws/eks-anywhere-internal/issues/2389)
Removing the `regionalBuildMode` option from the generatebundlefile CLI as we only run regional pipelines for generating and releasing packages bundles, helm charts and images. [#1137](https://github.com/aws/eks-anywhere-packages/pull/1137) removes all the non-regional bundle input files making the regional build mode env variable redundant as we always build in regional mode going forward.
=> Remove regional build mode option from generatebundlefile CLI

generatebundlefile/bundle.go
Adding creation timestamp to package bundles so that we can identify the latest created bundle by chronological order.
=> Add creation timestamp to package bundles

generatebundlefile/hack/common.sh, generatebundlefile/hack/release_prod.sh, generatebundlefile/input.go
We are changing the logic of packages bundles tagging to use the date and epoch time of the bundle creation instead of an arbitrary value like the CodeBuild build number.
=> Tag package bundles with epoch time and date of creation

generatebundlefile/hack/release_prod.sh, generatebundlefile/hack/release_staging.sh
This PR remove unnecessary helm charts promotion to public ECR registry in staging and prod release jobs as we now handle that in the ECR replication job. It also refactors the script to call the `generate` and `push` bundle functions in a single loop over kubernetes versions and update the comments to reflect what the job actually does.
=> Remove helm chart promotion to public ECR in staging and prod release

generatebundlefile/hack/common.sh
This PR removes the bundle diff check in bundle push method. 
=> Remove bundle diff check for staging and prod release

generatebundlefile/hack/common.sh
Removed reference of undefined method `removeBundleMetadata`.
=> fix: remove reference for undefined method removeBundleMetadata

generatebundlefile/hack/release_prod.sh
We don't need to set the `AWS_PROFILE` env var since we're pushing to the same account. 
=> Unset AWS_PROFILE env var in prod release script

generatebundlefile/ecr_helper.go
When generating the packages bundle, we only want to use artifacts built from main branch since we don't update and build packages from release branches. All artifacts built from main are tagged with `latest` so that makes it a useful filter.
=> Use only artifacts built from main branch in package bundle

generatebundlefile/README.md, generatebundlefile/bundle_test.go, generatebundlefile/ecr.go, generatebundlefile/ecr_helper.go
Currently, the dev packages bundles are generated based on the dev bundle input files defined [here](https://github.com/aws/eks-anywhere-packages/tree/main/generatebundlefile/data/bundles_dev) for each kubernetes version. Except for the package controller helm charts, all other packages helm charts have the "latest" version tag in the input file which tells the program to use a timestamp lookup and find the most recently pushed helm chart for information, even if that helm chart doesn't have the latest tag. This causes an issue when a certain package gets built from the release branch as that tag will be used in the dev packages bundle instead of the latest tag. Even if the packages helm chart have the same version/tag on the main and release branch, it could …
=> Use helm charts only from main branch when finding latest image tag

generatebundlefile/data/bundles_dev/1-31.yaml
Update  autoscaler and metrics-server version to 1.31 for dev bundles.
=> Fix  version for autoscaler and metrics-server

generatebundlefile/data/bundles_staging/1-26.yaml, generatebundlefile/data/bundles_staging/1-27.yaml, generatebundlefile/data/bundles_staging/1-28.yaml, generatebundlefile/data/bundles_staging/1-29.yaml, generatebundlefile/data/bundles_staging/1-30.yaml
This PR updates Prometheus version in staging bundle.
Node exporter image tag was missing corresponding to Prometheus chart git SHA, did the pipeline rebuild for both and updated the tag in staging bundle.
=> Packages staging release

generatebundlefile/data/bundles_dev/1-31.yaml
This PR reverts version update for autoscaler and metrics-server. Currently, there is no autoscaler chart for 1.31 Kubernetes version, which is causing the build pipeline for packages to fail at `Bundle Generation` stage.
Cluster-Autoscaler 1.31 still refers to 1.30 GIT_TAG as placeholder once we have updated the curated package, will update the dev-bundle to reflect correct version.
=> Revert autoscaler and metrics-server to 1.30 kubernetes version

generatebundlefile/data/bundles_dev/1-31.yaml
This PR updates the autoscaler and metrics-server version in the 1.31 dev bundle to start packages testing with Kubernetes v1.31.0.
=> Update autoscaler and metrics-server version in the 1.31 dev bundle

generatebundlefile/data/bundles_dev/1-27.yaml, generatebundlefile/data/bundles_dev/1-28.yaml, generatebundlefile/data/bundles_dev/1-29.yaml, generatebundlefile/data/bundles_dev/1-30.yaml, generatebundlefile/data/bundles_dev/1-31.yaml
Autoscaler was recently bumped to the latest version in [#3841](https://github.com/aws/eks-anywhere-build-tooling/pull/3841). This PR updates the autoscaler helm chart version to latest 9.40.0 in dev bundle.
=> Update autoscaler helm chart version to latest 9.40.0 in dev bundle

generatebundlefile/data/bundles_staging/1-31.yaml, generatebundlefile/hack/release_staging.sh
[#2399](https://github.com/aws/eks-anywhere-internal/issues/2399)
Add staging bundle for Kubernetes version 1.31
=> Add staging bundle for Kubernetes version 1.31

generatebundlefile/data/bundles_prod/1-31.yaml, generatebundlefile/hack/release_prod.sh
[#2399](https://github.com/aws/eks-anywhere-internal/issues/2399)
Add prod bundle for Kubernetes version 1.31
=> Add prod bundle for Kubernetes version 1.31

generatebundlefile/data/bundles_dev/1-27.yaml, generatebundlefile/data/bundles_dev/1-28.yaml, generatebundlefile/data/bundles_dev/1-29.yaml, generatebundlefile/data/bundles_dev/1-30.yaml, generatebundlefile/data/bundles_dev/1-31.yaml
Metrics server and Autoscaler charts were bumped to the latest version in [#3920](https://github.com/aws/eks-anywhere-build-tooling/pull/3920) and [#3922](https://github.com/aws/eks-anywhere-build-tooling/pull/3922) respectively. This PR updates them to the latest version in dev bundles.
=> Update autoscaler and metrics-server charts to latest version in dev bundles

credentialproviderpackage/pkg/configurator/linux/linux.go, credentialproviderpackage/pkg/configurator/linux/linux_test.go
- Removing unwanted feature gate option `KubeletCredentialProviders`. `KubeletCredentialProviders` feature gate was  GA'ed in `1.26` and was removed from `1.28`. For current supported release versions for EKS-A we don't need to add feature-gate option in kubelet-extra-args since the default option is `true` until 1.28 and is not available in later release versions 
Reference: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/
- Updated the unit test
*Testing*
- make test
- Functional testing was done along with this[ PR](https://github.com/aws/eks-anywhere-packages/pull/1177).
=> Removing unwanted feature gate(KubeletCredentialProviders) option

credentialproviderpackage/charts/credential-provider-package/templates/_helpers.tpl, credentialproviderpackage/charts/credential-provider-package/templates/daemonset.yaml, credentialproviderpackage/pkg/configurator/linux/linux.go, credentialproviderpackage/pkg/configurator/linux/linux_test.go
**What did we have before?**
- We used `/etc/sysconfig/kubelet` to update kubelet extra args with credential provider arguments.
- An upstream image-builder update added a new EnvironmentFile (/etc/default/kubelet).
- For Ubuntu, this new file took precedence, causing credential provider arguments to be updated in the wrong place.
- We reverted this change with a [patch](https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch).
**Changes Made:**
Updated the path KUBELET_EXTRA_ARGS file path for Ubuntu to `/etc/default/kubelet` so that credential provider arguments are updated in the right file for Ubuntu, also added KUBELET_EXTRA_ARGS_LEGACY to support older image templates …
=> Add support to update both legacy and default path for kubelet-extra-args for ubuntu

generatebundlefile/hack/update_bundles.sh
This PR introduces a new `update_bundles.sh` script that automates the process of updating input bundle files for both staging and production bundles for packages release. The script fetches the latest versions of packages from ECR and updates the corresponding YAML files for Kubernetes versions. This addition will streamline our bundle update workflow during packages release and reduce manual errors.
Tested script for both staging and prod bundles.
`sh update_bundles.sh -e staging`
=> Add update_bundle script to get latest version and update input bundle for staging and prod

charts/eks-anywhere-packages/templates/awssecret.yaml, charts/eks-anywhere-packages/templates/cronjob.yaml, charts/eks-anywhere-packages/templates/deployment.yaml, charts/eks-anywhere-packages/values.yaml, credentialproviderpackage/pkg/awscred/awscred.go, credentialproviderpackage/pkg/awscred/awscred_test.go, pkg/registry/ecr_cred_injector.go, tilt/deployment.yaml
https://github.com/aws/eks-anywhere-internal/issues/2650
https://github.com/aws/eks-anywhere-packages/issues/1182
https://github.com/aws/eks-anywhere-packages/issues/1181
Add session token in secret if available and use it in credential-package
*Testing*
Tested the changes by creating a cluster. verified that aws-secrets has session token and able to install curated package successfully. Tested current use case i.e. without session token and verified installation of packages succesful.
=> Use session token for ecr aws authentication

scripts/packages_image_scan.py
* Added CVE scanner script to check for CRITICAL vulnerabilities in curated package images, script uses package bundle as input file and queries inspector scan result to generate report.
* **Prerequisite**: Enable inspector scanning on the AWS account which has package bundle, and which we will be using to generate report.
* Set AWS credentials for the account
* Download package bundle: `oras pull $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/eks-anywhere-packages-bundles:v1-30-latest`
* Run script `python packages_image_scan.py --bundle path/to/bundle/file`
=> feat: add CVE scanner script for critical vulnerabilities in curated package images

generatebundlefile/data/bundles_dev/1-33.yaml, generatebundlefile/data/bundles_prod/1-33.yaml, generatebundlefile/data/bundles_staging/1-33.yaml
Autoscaler upstream does not have support for 1.33 yet. Use 1.32 for autoscaler until 1.33 upstream support is released
=> Use 1.32 for autoscaler until 1.33 upstream support is released

charts/eks-anywhere-packages/templates/credentialpackage.yaml, credentialproviderpackage/charts/credential-provider-package/templates/daemonset.yaml, credentialproviderpackage/charts/credential-provider-package/values.yaml, credentialproviderpackage/pkg/configurator/bottlerocket/bottlerocket.go, credentialproviderpackage/pkg/configurator/linux/linux.go, credentialproviderpackage/pkg/configurator/linux/templates/credential-provider-config.yaml, credentialproviderpackage/pkg/configurator/proxy.go
https://github.com/aws/eks-anywhere-internal/issues/3528
When using curated packages with proxy configured in an airgapped environment, ecr-credential-provider kubelet plugin will fail to retrieve ecr credentials. The request times out as it's not configured to use proxy. Following error is observed from kubelet service logs
```
Aug 13 20:47:12 ub130pkgproxy-md-0-tkzgw-gjcgl kubelet[4170]: E0813 20:47:12.329512    4170 plugin.go:235] Failed getting credential from external registry credential provider: error execing credential provider plugin ecr-credential-provider for image 067575901363.dkr.ecr.us-west-2.amazonaws.com/hello-eks-anywhere: context deadline exceeded: I0813 20:46:12.343864    5769 main.go:124] Getting creds for private …
```
=> Pass proxy env vars to ecr credential provider

generatebundlefile/data/bundles_prod/1-28.yaml, generatebundlefile/data/bundles_prod/1-29.yaml, generatebundlefile/data/bundles_prod/1-30.yaml, generatebundlefile/data/bundles_prod/1-31.yaml, generatebundlefile/data/bundles_prod/1-32.yaml, generatebundlefile/data/bundles_prod/1-33.yaml
- Update package prod bundle to latest version
-  eks-anywhere-packages
- metallb
- cluster-autoscaler for kubernetes version 1.33 
=> Update prod bundle for package release
